
:fragment:

From the technical point of view, the actual _core_ of the extensible Spring context {framework} provides is defined in the main configuration file: `org/altemista/cloudfwk/config/core/altemista-cloudfwk-core.xml`.

CAUTION: The actual boostrap of the Spring context is done at the aggregator project as its own nature requires (e.g.: a web application and a Spring Boot-based application bootstraps the Spring context differently). Without an aggregator project, the main configuration file of {framework} is not loaded.

This configuration file runs a component scan for annotated beans under the package `org.altemista.cloudfwk.core`.

It also automatically imports the configuration of any {framework} core module present in the classpath, including self. The hierarchical structure of configuration is as follows in the next example (packages removed for clarity):

* `altemista-cloudfwk-core.xml` imports `altemista-cloudfwk-core-*.xml`
** `altemista-cloudfwk-core-<feature>.xml` import `altemista-cloudfwk-<feature>-<implementation>.xml`
** `altemista-cloudfwk-core-web.xml` import `altemista-cloudfwk-web-*.xml`
*** `altemista-cloudfwk-web-<web-feature>.xml` import `altemista-cloudfwk-web-<web-feature>-<implementation>.xml`
** etcetera

Another notable configuration file is `org/altemista/cloudfwk/config/core/altemista-cloudfwk-init.xml`, which ends up being the first configuration file to be processed. This file contains the configuration that must be included before any other {framework} or application configuration file.

Namely, this file contains configuration for the environment dependent Logback configurator:

[source,xml,options="nowrap"]
.org/altemista/cloudfwk/config/core/altemista-cloudfwk-init.xml
----
include::{basedir}/altemista-cloudfwk-core/src/main/resources/org/altemista/cloudfwk/config/core/altemista-cloudfwk-init.xml[tags=internalsLogback]
----

The configuration for the other features of the core nature are loaded normally, as if they were stand-alone features: internationalization (i18n), logging (such as the exception logger aspect) and Java Management Extensions (JMX).
