package cloud.altemista.fwk.remindersmybatis.module.repository;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import cloud.altemista.fwk.remindersmybatis.module.model.RmndrsTable;
import cloud.altemista.fwk.remindersmybatis.module.model.RmndrsTableExample;

public interface RmndrsTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_TABLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int countByExample(RmndrsTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_TABLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int deleteByExample(RmndrsTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_TABLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_TABLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int insert(RmndrsTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_TABLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int insertSelective(RmndrsTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_TABLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    List<RmndrsTable> selectByExampleWithRowbounds(RmndrsTableExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_TABLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    List<RmndrsTable> selectByExample(RmndrsTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_TABLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    RmndrsTable selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_TABLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int updateByExampleSelective(@Param("record") RmndrsTable record, @Param("example") RmndrsTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_TABLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int updateByExample(@Param("record") RmndrsTable record, @Param("example") RmndrsTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_TABLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int updateByPrimaryKeySelective(RmndrsTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_TABLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int updateByPrimaryKey(RmndrsTable record);
}