package cloud.altemista.fwk.remindersmybatis.module.repository;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import cloud.altemista.fwk.remindersmybatis.module.model.RmndrsUserRole;
import cloud.altemista.fwk.remindersmybatis.module.model.RmndrsUserRoleExample;

public interface RmndrsUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_USER_ROLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int countByExample(RmndrsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_USER_ROLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int deleteByExample(RmndrsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_USER_ROLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_USER_ROLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int insert(RmndrsUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_USER_ROLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int insertSelective(RmndrsUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_USER_ROLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    List<RmndrsUserRole> selectByExampleWithRowbounds(RmndrsUserRoleExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_USER_ROLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    List<RmndrsUserRole> selectByExample(RmndrsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_USER_ROLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    RmndrsUserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_USER_ROLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int updateByExampleSelective(@Param("record") RmndrsUserRole record, @Param("example") RmndrsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_USER_ROLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int updateByExample(@Param("record") RmndrsUserRole record, @Param("example") RmndrsUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_USER_ROLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int updateByPrimaryKeySelective(RmndrsUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_USER_ROLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int updateByPrimaryKey(RmndrsUserRole record);
}