
:fragment:

[[altemista-cloudfwk-app-security-conf-configuration-authentication]]
== Authentication managers

The security feature of the framework provides a hook into the Spring Security web infrastructure. The application must provide the authentication mechanism and the the users repository (e.g.: in-memory, database, LDAP, etc.).

[source,xml]
.spring/my-application-security-authentication-env.xml
----
include::{basedir}/altemista-cloudfwk-app-security-conf/src/test/resources/spring/security-example-simple.xml[tags=authentication]
----
<1> When security is enabled, an authentication service must be provided to the application.
<2> In this example, a simple in-memory user repositoy is set up with two users: `user` and `admin`.

TIP: For further information on the existing authentication managers (e.g.: LDAP, database-based, etc.), refer to the _Authentication_ chapter of the http://docs.spring.io/spring-security/site/docs/current/reference/html/[Spring Security Reference]. 

[[altemista-cloudfwk-app-security-conf-configuration-http]]
== HTTP security

The minimal HTTP Security configuration (XML-based approach) is as follows:

[source,xml]
.spring/my-application-webapp-security-http.xml
----
include::{basedir}/altemista-cloudfwk-app-security-conf/src/test/resources/spring/security-example-minimal.xml[tags=example]
----
<1> This removes entirely the authentication from web security, as well as URIs authorizations.

IMPORTANT: With this configuration, there will not be any Authentication object in the SecurityContext. This means that annotation secured methods will no longer be allowed to be executed, even if their security is `@Secured("IS_AUTHENTICATED_ANONYMOUSLY")`, `@PreAuthorize("isAuthenticated()")` or JSR 250 `@PermitAll`.

A more useful -but still rather simplistic- configuration that can serve as a starting point for the definition of the HTTP security in any application:

[source,xml]
.spring/my-application-webapp-security-http.xml
----
include::{basedir}/altemista-cloudfwk-app-security-conf/src/test/resources/spring/security-example-simple.xml[tags=http]
----
<1> Chooses which authentication manager this HTTP security element will use.
<2> The `<security:form-login>` element provides authentication on demand. With an empty configuration, it also generates a login page at the `/login` mapping.
<3> The `<security:http-basic>` element includes the processing of basic authentication credentials presented in HTTP headers, as defined by http://www.rfc-base.org/rfc-1945.html[RFC 1945] (Base64 encoding of the `username:password`, specified in an HTTP header).
<4> The `<security:logout>` element adds support for logging out by navigating to a particular URL. The default default logout URL is `/logout`.
<5> HTTP security elements are usually composed of multiple `<security:intercept-url>` elements. +
In this example, URIs starting with `/secure/{asterisk}{asterisk}` will require the user to be authenticated, and URIs matched by `/{asterisk}{asterisk}` will be accessible by any user, even not authenticated users. +
The difference with the previous _minimal HTTP security_ example is that, while `access="permitAll"` configures authorization, `filters="none"` does not.

TIP: For further information on HTTP security (e.g.: how to configure a custom log-in page), refer to the http://docs.spring.io/spring-security/site/docs/current/reference/html/[Spring Security Reference].
