
:fragment:

The _WS-Security for SOAP server_ feature augments the SOAP web service publisher feature to support Spring Security-based inbound WS-Security.

== Publishing SOAP web services with WS-Security

This feature defines some classes to simplify the implementation of inbound WS-Security, and declares, out-of-the-box, a web service feature named `inboundWssFeature` and `UsernameTokenValidator`. Both perform inbound WS-Security in a configurable manner and automatically integrate with Spring Security. Usually, only one of them will be enabled at the same time.

Please, read the <<cloud-altemistafwk-web-soap-wss-conf-configuration,configuration>> section to know how to properly set up inbound WS-Security.

== Creating custom WSS4J interceptors

For special cases, it is possible to declare you own WSS4J interceptors benefiting from the base classes provided by the framework:

`Wss4jInterceptorFeature`::

Base adapter of CXF-specific `WSS4JInInterceptor` or `WSS4JOutInterceptor` as a standard `WebServiceFeature` (e.g.: to be used in Spring `AbstractJaxWsServiceExporter`).

`Wss4jInInterceptorFeature`::

Adapter of CXF-specific `WSS4JInInterceptor` as a standard `WebServiceFeature`.

Please refer to the Javadoc of these classes for further information.
