
:fragment:

===== Entity DTO
[source,java,linenums]
./AltemistaMoviesMovies-client/src/main/java/cloud/altemista/fwk/demo/altemistaMoviesmovies/microservice/domain/MovieDTO.java
----
public class MovieDTO {
	
   private Long id;
   private String title;

	<1>	
}
----
<1> Getters and setters

===== Microservice interface

First of all you have to rename the `MicroserviceExample` class. The new name will be `AltemistaMoviesMovies`.

[NOTE]
====
You have to add the org.springframework.data:spring-data-commons dependency to add Pageable Spring Data feature

[source,xml]
./AltemistaMoviesMovies-client/pom.xml
----
<dependency>
	<groupId>org.springframework.data</groupId>
	<artifactId>spring-data-commons</artifactId>
	<scope>provided</scope>
</dependency>
----
====

[[movies-interface]]
[source,java,linenums]
.AltemistaMoviesMovies.java
----
package cloud.altemista.fwk.demo.altemistaMoviesmovies.microservice.service;

import java.util.List;
import java.util.Map;

import org.springframework.cloud.netflix.feign.FeignClient;
import org.springframework.data.domain.Pageable;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import cloud.altemista.fwk.demo.altemistaMoviesmovies.microservice.domain.MovieDTO;

@FeignClient("AltemistaMoviesMovies")
public interface AltemistaMoviesMovies {

	@RequestMapping(value = "/", method = RequestMethod.GET)
	ResponseEntity<List<MovieDTO>> listAllMovies(Pageable page); // <1>

	@RequestMapping(value = "/{id}", method = RequestMethod.GET)
	ResponseEntity<MovieDTO> getMovie(@PathVariable("id") long id); // <2>

	@RequestMapping(value = "/", method = RequestMethod.POST)
	ResponseEntity<MovieDTO> createMovie(@RequestBody MovieDTO movieDTO); // <3>

	@RequestMapping(value = "/{id}", method = RequestMethod.PUT)
	ResponseEntity<MovieDTO> updateMovie(@PathVariable("id") long id, @RequestBody MovieDTO movieDTO); // <4>

	@RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
	ResponseEntity<MovieDTO> deleteMovie(@PathVariable("id") long id); // <5>
	
	@RequestMapping(value = "/queryHealth", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
	@ResponseBody ResponseEntity<Map<String, String>> queryHealth();

}
----

<1> This method gets all Movies.
<2> This method gets a Movie by ID.
<3> This method creates a Movie.
<4> This method updates a Movie.
<5> This method deletes a Movie.

IMPORTANT: You can delete the example classes generated by the archetype like `MicroserviceExampleRequest` and `MicroserviceExampleResponse`. 