
:fragment:

This guide describes the continuous integration (CI) server setup for {framework}.

Currently, the CI server is located at the URL: https://terasoluna.everis.com. The only ports available to access (due to firewall rules) are 80 and 443.

The next sections contain a non-comprehensive list of the software used for the {framework} lifecycle management.

=== Apache HTTP Server

An instance of https://httpd.apache.org/[Apache HTTP Server Project] is installed to centralise the access to the different tools.

The installation process is as follows:

[source,bash]
----
sudo yum install httpd
----

The contents of the configuration file (`/etc/httpd/conf.d/vhosts.conf`) are:

[source,vhosts]
./etc/httpd/conf.d/vhosts.conf
----
NameVirtualHost 7.128.81.57:80
<VirtualHost 7.128.81.57:80>
ServerName www.tsfplus.its.everis.com
ServerAlias www.tsfplus.its.everis.com tsfplus.its.everis.com
DocumentRoot /var/www/html/
CustomLog /etc/httpd/logs/tsfplus.access_log combined
ErrorLog /etc/httpd/logs/tsfplus.error_log

# Jenkins
ProxyPass         /jenkins  http://localhost:8080/jenkins nocanon
ProxyPassReverse  /jenkins  http://localhost:8080/jenkins
ProxyRequests     Off
AllowEncodedSlashes NoDecode
<Proxy http://localhost:8080/jenkins*>
  Order deny,allow
  Allow from all
</Proxy>

# Sonarqube
ProxyPass         /sonar  http://localhost:9000/sonar nocanon
ProxyPassReverse  /sonar  http://localhost:9000/sonar
ProxyRequests     Off
AllowEncodedSlashes NoDecode
<Proxy http://localhost:9000/sonar*>
  Order deny,allow
  Allow from all
</Proxy>

</virtualhost>
----

////
# Docker-UI (currently not working)
# Check https://portainer.readthedocs.io/en/stable/faq.html
ProxyPass         /portainer  http://localhost:9010 nocanon
ProxyPassReverse  /portainer  http://localhost:9010
ProxyRequests     Off
AllowEncodedSlashes NoDecode
<Proxy http://localhost:9010*>
  Order deny,allow
  Allow from all
</Proxy>
////

This Apache HTTP Server instance is currently exposing the path `/var/www/html` to http://tsfplus.its.everis.com/

It is also providing entry points to the Jenkins and SonarQube instances.

==== {framework} page

The {framework} page (or {framework} portal) is a static page.

Its contents are located at the path `/var/www/html`.

==== Legacy j-everis binaries

Binaries of the legacy j-everis framework are served under the path http://tsfplus.its.everis.com/j-everis

The actual contents are located at the path `/opt/j-everis`, which is aliased as `/var/www/html/j-everis`.

==== {framework} binaries

Binaries and other downloadable material of {framework} is served under the path https://terasoluna.everis.com/downloads

These actual contents are located at the path `/opt/tsfp-bin`, which is aliased on nginx configuration.

==== {framework} plug-in update site

In order to allow existing {framework} installations to update the plug-in, the update site is served at https://terasoluna.everis.com/update-site.

The actual contents of the update site are located at the path `/opt/tsfp-updatesite`, which is aliased on nginx configuration .

=== Java Runtime Environment (JRE)

A default Java installation is required to support other tools (such as Jenkins and SonarQube):

[source,bash]
----
sudo yum install java
----

=== Jenkins

https://jenkins.io/[Jenkins] is an open source automation server written in Java. The latest LTS vesion (namely, 2.32.3 at the time of writing) has been installed.

The configuration file `/etc/sysconfig/jenkins` has been modified to:

* Set `/jenkins` as the context path: `JENKINS_ARGS="--prefix=/jenkins"`, so it is deployed at http://tsfplus.westeurope.cloudapp.azure.com:9090.

* Set a different Jenkins home: `JENKINS_HOME="/opt/jenkins"`. All the configuration files are located in that JENKINS_HOME (`/opt/jenkins`). This folder should be owned by the user `jenkins`.

The installation process is as follows:

[source,bash]
----
sudo wget
	-O /etc/yum.repos.d/jenkins.repo
	-e use_proxy=yes
	-e http_proxy=http://10.0.8.102:8080
	http://pkg.jenkins-ci.org/redhat-stable/jenkins.repo

sudo rpm
	--import https://jenkins-ci.org/redhat/jenkins-ci.org.key
	--httpproxy http://10.0.8.102
	--httpport 8080

sudo yum install jenkins
----

=== SonarQube

https://www.sonarqube.org/[SonarQube] is an open source platform for continuous inspection of code quality. The lastest LTS version (namely, 5.6.1 at the time of writing) has been installed.

The installation path is `/opt/sonar`, and it is deployed at http://tsfplus.its.everis.com/sonar.

The configuration has been kept with all the default values, except for the context path.

=== Java Development Kits (JDKs)

A set of different versions of the Java Development Kits (JDKs) will be used by Jenkins to build and test the framework.

The different JDKs are installed at `/opt/jdk/<concrete version>`.

=== Maven

https://maven.apache.org/[Apache Maven] will be installed at `/opt/mvn/<concrete version>`. Different versions can be maintained to test the framework building process with different configurations.

All the Maven installations will share the same maven repository: `/opt/maven-repository`

=== Integration Test Servers

The different servers to be used in the integration test phase are located under the following paths:

* `/opt/jee-servers`: Java EE Application servers, such as Apache Tomcat or WildFly.

* `/opt/db-servers`: database servers, such as MySQL or PostgreSQL.

* `/opt/mq-servers`: Message Queue servers, such as RabbitMQ, ActiveMQ or Kafka.

////
## Docker

Currently installed but not in use. We are planning to install some application
such as Portainer to have a user interface to view the status of the containers and operate them.
////

=== Additional considerations

Please, note that the CI server requires to setup a proxy. At the moment, the current proxy is `http://10.0.8.102:8080` (as shown in the example commands of this chapter).

Start of some services could not be activated during boot process.

Please, verify the status and enable it if necessary using the following command:

[source,bash]
----
sudo systemctl enable jenkins.service
----
