
:fragment:

== Packaging and naming conventions

All packages of the framework start by `org.altemista.cloud`:

* `org.altemista.cloudfwk.common` contains _common_ nature related classes.
+
Expected subpackages: `<feature>.exception` for `CommonException` and its children, `<feature>.model` for business model, and `<feature>.util` for utility classes.

* `org.altemista.cloudfwk.core` contains _core_ nature related classes.
+
Expected subpackages: `<feature>.exception` for `CoreException` and feature exceptions, `<feature>.bean` for Spring beans, `<feature>.service` for interfaces to the services of the features, and `<feature>.util` for utility classes.

* `org.altemista.cloudfwk.web` contains _web_ nature related classes.
+
Expected subpackages: `<feature>.exception` for `WebException` and web-tier feature exceptions, and `<feature>.filter` for JAVA EE filters.

* `org.altemista.cloudfwk.webapp` contains _webapp_ nature related classes.

This does not only apply to Java classes, but to properties and configuration files:

* `org.altemista.cloudfwk.i18n` for internationalization messages, usually with the name `<artifactId>-messages.properties` (e.g.: `altemista-cloudfwk-common-messages.properties`).

* `org.altemista.cloudfwk.config` for auto-discoverable configuration files (see <<natures-core-internals,_core_ configuration of the framework>> for an explanation on the auto-discovery mechanism of {framework}).
+
Expected subpackages and files: `core`, `web`, `webapp`, and `boot` for the auto-discoverable configuration of each nature related features.
+
Also, it is expected to found `<feature>` subpackages the auto-discoverable configuration of implementation providers of an specific feature.

Please refer to the code of existing features to find examples of this packaging schema. Also, note that this packaging convention is not strict, and can be changed _ad-hoc_ to favor readability and API discoverability (e.g.: extracting service interfaces to the base package).

== Developing a new feature

A new {framework} feature will usually be a new set of Maven projects following a predefined structure.

The parent `pom.xml` of the new feature will be as follows:

[source,xml]
.altemista-cloudfwk-newfeature/pom.xml
----
<project ...>
	
	<parent>
		<groupId>org.altemista.cloudfwk.build</groupId>
		<artifactId>altemista-cloudfwk-build</artifactId> <!--1-->
		<version>1.0.0.RELEASE</version>
		<relativePath>..</relativePath>
	</parent>
	
	<artifactId>altemista-cloudfwk-newfeature</artifactId> <!--2-->
	<packaging>pom</packaging>

	<name>altemista-cloudfwk * newfeature build script</name> <!--3-->
	
	<profiles>
		<!-- == Builds ACF framework == -->
		<profile>
			<id>framework</id>
			<modules>
				<module>altemista-cloudfwk-core-newfeature</module>
				<module>altemista-cloudfwk-core-newfeature-conf</module>
				<module>altemista-cloudfwk-core-newfeature-archetype</module> <!--4-->
			</modules>
		</profile>
		
		<!-- == Builds and run ACF integration tests == -->
		<profile>
			<id>run-it</id>
			<modules>
				<module>altemista-cloudfwk-core-newfeature-it</module> <!--5-->
			</modules>
		</profile>
	</profiles> 

</project>
----
<1> Use the {framework} build script as the local parent of the build script of the new feature.
<2> The name of the build script of the new feature will follow the convention `altemista-cloudfwk-<feature name>`.
<3> The build script of the new feature is simply a build script. It contains neither code nor configuration.
<4> The actual projects containing the code, the configuration and the archetypes will be specified as `<modules>` in the `framework` profile.
<5> The projects containing the integration tests will be specified as `<modules>` in the `run-it` profile.

=== Simple feature project structure

Depending on the type of feature, the set of projects to implement it will be quite different. To set a starting point, a typical feature will be composed of four projects:

* `altemista-cloudfwk-<nature>-<feature>` will contain the feature classes of the new feature for projects with the specified nature. In the previous example, the feature is installed on _core_ projects. This project will be added as a _compile_ dependency to the business module project that uses the feature, and will likely be used by the plug-in to detect the feature as installed.
+
Please note that the nature in the project name is orientative; some features can be installed in more than one nature (e.g.: `altemista-cloudfwk-common-connection` can be installed in both _common_ and _core_ projects). In that case, prefer the less restrictive nature for naming the feature.
+
In addition to the usual natures, the fake _app_ nature can be used to indicate a feature that is to be installed on the aggregator project (e.g.: `altemista-cloudfwk-app-performance` can be installed in both _webapp_ and _boot_ projects).

* `altemista-cloudfwk-<nature>-<feature>-conf` will contain the auto-discoverable configuration of the new feature and the unit test that depend on the Spring context. This project is likely to be added as a _runtime_ dependency of the shared environment project.

* `altemista-cloudfwk-<nature>-<feature>-archetype` will be the partial archetype containing the dependencies and the minimal configuration files to install the feature.

* `altemista-cloudfwk-<nature>-<feature>-it` will contain the integration tests of the feature.

=== Feature and implementation project structure

When creating a feature with a clear separation between the interface and the implementation (e.g.: the BPM feature), the naming of the projects is usually as follows:

* `altemista-cloudfwk-<nature>-<feature>` for the interface.

* `altemista-cloudfwk-<nature>-<feature>-<implementation>` for the classes of a concrete implementation.

* `altemista-cloudfwk-<nature>-<feature>-<implementation>-conf` for the auto-discoverable configuration of the concrete implementation.

* `altemista-cloudfwk-<nature>-<feature>-<implementation>-archetype` for the partial archetype to install the concrete implementation.

=== Tiered feature project structure

When creating a feature that applies to both business and web tier (e.g.: the monitoring feature), it is not unusual to have a _common_ project to communicate both tiers of the feature. Despite the name, this does not imply that the feature is available for _common_ nature projects.

* `altemista-cloudfwk-common-<feature>` for the interface between the web-tier and the business-tier of the feature. Usually, the web-tier will consume the interface and the business-tier will implement it.

=== Including the new feature in {framework} plug-in

Please refer to the <<altemista-cloudfwk-documentation-developers-plugin-configuration-features,plug-in features configuration>> section.
