
:fragment:

== Resource Owner Password Credentials Grant

As a general rule, a web application *should not use* Resource Owner Password Credentials Grant.

However, if it is a mandatory requirement to use password grants in a {framework} application, please refer to to the http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/en/Security/OAuth.html#settings-of-resource-at-the-time-of-using-resource-owner-password-credential-grant[Settings of resource at the time of using resource owner password credential grant] section of the http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/en/[TERASOLUNA Server Framework for Java (5.x) Development Guideline] to know how to properly set-up the `OAuth2RestTemplate` object.

== Implicit grant

The type of authorization Implicit Grant typically used when the client is running in a browser using a scripting language such as *JavaScript*, which is outside the scope of {framework}.

Please refer to the http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/en/Security/OAuth.html#accessing-a-resource-using-javascript[Accessing a resource using JavaScript] section of the http://terasolunaorg.github.io/guideline/5.3.0.RELEASE/en/[TERASOLUNA Server Framework for Java (5.x) Development Guideline] for details on how to implement a JavaScript client using a ready-made function (`oauth2.js`).
