
:fragment:

The default configuration of the Activiti BPM implementation is as follows:

[source,xml,options="nowrap"] 
.org/altemista/cloudfwk/config/workflow/altemista-cloudfwk-workflow-activiti.xml
----
include::{basedir}/altemista-cloudfwk-core-workflow-activiti-conf/src/main/resources/org/altemista/cloudfwk/config/workflow/altemista-cloudfwk-workflow-activiti.xml[tags=internals]
----
<1> The <<altemista-cloudfwk-core-workflow-activiti-conf-configuration,aforementioned required bean `workflowDataSource`>>.
<2> The `databaseSchemaUpdate` allows to set the strategy Activiti will use to handle the database. To allow new applications to start working with the workflow module immediately, the framework sets by default this value to `true` (the schema will be updated or, if it doesn't exist, created) instead of original Activiti default value `false` (throw an exception if the schema version does not match). A third, the more aggresive, value `create-drop` can be used. Refer to the Activiti documentation for further details.
<3> The framework follows the Activiti recommendation of using the new `AsyncExecutor` instead of the legacy `JobExecutor` to fire timers and asynchronous tasks. 
<4> The process engine is configured to automatically deploy the resources (i.e.: process definitions) found in the classpath, inside the `workflow` package and with the standard extension `.bpmn20.xml`. Please refer to the Activiti user guide for details about automatic resource deployment modes.

NOTE: This default configuration is intended to embed Activiti inside an application and will most likely change for other uses, such as connecting to an existing Activiti installation.

As usual, if the desired configuration can not be achieved by parameterizing the default configuration, the application can override the definition of the bean `processEngineConfiguration`.
