
:fragment:

The executor and scheduler the module sets up for supporting asynchronous and scheduled executions come with a sensitive default values that suffice for development stages and simple projects. However, these values can be set through properties in the application:

[source,properties]
.config/properties/my-application-async-env.properties
----
include::{basedir}/altemista-cloudfwk-core-async-conf/src/test/resources/config/properties/test-async-env.properties[]
----

TIP: If changing this configuration values is not enough, refer to the <<altemista-cloudfwk-core-async-conf-internals,internals>> of this module to override these beans.

In order to use the asynchronous executions register, at least one `AsyncStoragePolicy` bean is required. By example, to declare a bean using the in-memory map based storage policy provided by the framework:

[source,xml]
.spring/my-application-module-core.xml
----
include::{basedir}/altemista-cloudfwk-core-async-conf/src/test/resources/spring/altemista-cloudfwk-test-async-storagePolicy.xml[tags=storagePolicy]
----
<1> Maximum time that a completed tasks is to be kept (in seconds). The default is 60 seconds (1 minute).
<2> Maximum time that a pending tasks is to be kept (in seconds). The default is 300 seconds (5 minutes).
