
:fragment:

Though originally developed for internal use only, the `cloud-altemistafwk-test` artifact is published in order to both simplify the `test` scoped dependencies, and to provide some utility classes to the applications.

== Writing Spring context-aware unit tests

To tests Spring beans (i.e.: classes and methods that make use of the Spring context), such as services, is not unusual for these beans to have dependencies to {framework} features.

In order to have the proper dependencies set up as they will be in the application, extend `AbstractSpringContextTest` in the test class:

[source]
.SpringContextTest.java
----
include::{basedir}/cloud-altemistafwk-test/src/test/java/cloud/altemista/fwk/test/SpringContextTest.java[tags=example]
----
<1> The `AbstractSpringContextTest` is a convenience base class that loads the core {framework} Spring application context without aggregator-specific bean (such as _webapp_ or _boot_ modules), and without the application specific configuration files (i.e.: `/spring/*.xml`).

IMPORTANT: This will set up the features of the current business module implementation *only*, as the dependency to other business modules will be to their interfaces.

Usually, tests require to set up some additional application beans. This can be achieved as follows:

[source]
.SpringContextTest.java
----
include::{basedir}/cloud-altemistafwk-test/src/test/java/cloud/altemista/fwk/test/CustomSpringContextTest.java[tags=example]
----
<1> The test can declare the configuration files it needs only.

== Convenience constants

The utility class `TestConstants` provides some convenience constants that can be used in tests. They are all build around the standard _Lorem Ipsum_ passage (for text-related constants), and around a random picture of 32x32 pixels (for binary-related constants).

This values are available as `String`, byte arrays, instances of `ContentReadable`, backed by a Spring resource, etc.

Please refer to the Javadoc of the class for further information.

== Latency simulation

In order to write tests involving latency (e.g.: to test asynchronous executions), there are two utility classes provided by the framework:

`SlowByteArrayInputStream`::

Acts as a `ByteArrayInputStream` that takes at least one millisecond to read every byte. To be used where a latency reading from an array is to be simulated.

`SlowInputStreamSource`::

Implementation of `InputStreamSource` that returns a fresh `SlowByteArrayInputStream` on each call. To be used where a latency reading from an array is to be simulated and a fresh `InputStream` should be created on each call.

NOTE: For slowly readable implementations of `ContentReadable`, please check the proper methods of `TestConstants`.
