package com.mycompany.application.module.repository;

/*
 * #%L
 * altemista-cloud persistence: MyBatis integration tests
 * %%
 * Copyright (C) 2017 NTT DATA Corporation
 * %%
 * All rights reserved.
 * Todos los derechos reservados.
 * #L%
 */


import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.mycompany.application.module.model.DemoTable;
import com.mycompany.application.module.model.DemoTableExample;

public interface DemoTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    int countByExample(DemoTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    int deleteByExample(DemoTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    int deleteByPrimaryKey(Integer key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    int insert(DemoTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    int insertSelective(DemoTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    List<DemoTable> selectByExampleWithRowbounds(DemoTableExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    List<DemoTable> selectByExample(DemoTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    DemoTable selectByPrimaryKey(Integer key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    int updateByExampleSelective(@Param("record") DemoTable record, @Param("example") DemoTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    int updateByExample(@Param("record") DemoTable record, @Param("example") DemoTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    int updateByPrimaryKeySelective(DemoTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    int updateByPrimaryKey(DemoTable record);
}
