
:fragment:

In order for a web application to be an OAuth 2.0 Client using the Authorization Code Grant flow, declare the `OAuth2RestTemplate` object as follows:

.spring/new-application-webapp-oauth2-client.xml
[source,xml]
----
<oauth2:resource id="authorizationCodeResource"
	type="authorization_code"
	client-id="example" client-secret="3Zeh4eNw" scope="EXAMPLE"
	access-token-uri="http://{authorizationserver}/oauth/token"
	user-authorization-uri="http://{authorizationserver}/oauth/authorize"
	pre-established-redirect-uri="http://{resourceserver}/" /> <!--1-->

<oauth2:rest-template id="authorizationCodeRestTemplate"
	resource="authorizationCodeResource" /> <!--2-->
----
<1> Use the `<oauth2:resource>` to define the detailed information of the resource to be accessed.
<2> Use the `<oauth2:rest-template>` to declare the actual `OAuth2RestTemplate` object.

This `RestTemplate` object will actually throw a `UserRedirectRequiredException` exception the first time the client tries to access the resource server, and will automatically trigger the proper redirection for the user to log in and authorize the client.

In order for the client to be able to parse the authorization code and exchange it for the access token, there is a security filter for OAuth 2.0 Client (namely, `OAuth2ClientContextFilter`). This filter instance is provided by the framework itself, but it should be mapped to the URL patterns of the client as follows:

.WEB-INF/web.xml
[source,xml]
----
<!-- Applies the security filter for the OAuth 2.0 Client mappings -->
<filter>
	<filter-name>oauth2ClientContextFilter</filter-name>
	<filter-class>org.springframework.web.filter.DelegatingFilterProxy</filter-class>
</filter>
<filter-mapping>
	<filter-name>oauth2ClientContextFilter</filter-name>
	<url-pattern>/*</url-pattern> <!--1-->
</filter-mapping>
----
<1> Since the `OAuth2ClientContextFilter` filter generates the redirection after the authorization process has been completed, please consider a narrower definition (e.g. `/client/{asterisk}` instead of `/{asterisk}`) to the mappings that actually can invoke the resource server.
