
:fragment:

////
	Note: this fragment uses the _ifndef_ conditional preprocessor directive
	to exclude advanced topics if _getting-started_ is defined
////

The MyBatis-based implementation of the persistence feature sets up most of the necessary infrastructure to start MyBatis, except for the JDBC data source and the mapper scanner.

The <<cloud-altemistafwk-core-persistence-mybatis-conf-internals,infrastructure definded by the framework>> reads some convenient values from the configuration of the application:

[source,properties]
.config/properties/cloud-altemistafwk-test-persistence-mybatis-env.properties
----
include::{basedir}/cloud-altemistafwk-core-persistence-mybatis-conf/src/test/resources/config/properties/cloud-altemistafwk-test-persistence-mybatis-env.properties[]
----

The JDBC data source, named `myBatisDataSource`, must be provided by the application. Either by declaring a separate data source or aliasing an existing one:

[source,xml]
.spring/my-application-persistence-mybatis-env.xml
----
include::{basedir}/cloud-altemistafwk-core-persistence-mybatis-conf/src/test/resources/spring/cloud-altemistafwk-example-mybatis.xml[tags=datasource]
----

It is also reponsability of the {framework} applications to create instances for the repository interfaces defined:

[source,xml]
.spring/my-application-module-persistence-mybatis.xml
----
include::{basedir}/cloud-altemistafwk-core-persistence-mybatis-conf/src/test/resources/spring/cloud-altemistafwk-example-mybatis.xml[tags=repositories]
----
<1> The transactional behavior based on annotations can be configured to also use the transaction manager provided by the framework.

ifndef::getting-started[]
== MyBatis configuration file

The http://www.mybatis.org/mybatis-3/configuration.html[MyBatis Configuration] file must be found in the config/mybatis/mybatis-config.xml path in the classpath, and should be provided by the application. If this feature is installed with the ACF plug-in, this file will be included with a default configuration as follows:

[source,xml,options="nowrap"]
./cloud-altemistafwk-core-persistence-mybatis-conf/src/test/resources/config/mybatis/mybatis-config.xml
----
include::{basedir}/cloud-altemistafwk-core-persistence-mybatis-conf/src/test/resources/config/mybatis/mybatis-config.xml[]
----

For a complete description, check the http://www.mybatis.org/mybatis-3/configuration.html[MyBatis Configuration] page of the http://www.mybatis.org/mybatis-3/[MyBatis Reference Documentation].
endif::getting-started[]

[[cloud-altemistafwk-core-persistence-mybatis-conf-configuration-generator]]
== MyBatis Generator configuration file

The MyBatis Generator configuration file `generatorConfig.xml` is located at the `src/main/resources` folder. If this feature is installed with the ACF plug-in, this file will be included with a default configuration as follows:

[source,xml]
.generatorConfig.xml
----
include::{basedir}/cloud-altemistafwk-core-persistence-mybatis-conf/src/test/resources/generatorConfig.xml[]
----
<1> The context specifies the environment for each set of objects. A single context would usually suffice, but multiple contexts can be declared if necessary.
<2> The configuration provided by {framework} includes a set of convenient plugins. Namely, the generated entities will implement `Serializable` and have default `hashCode`, `equals` and `toString` implementations. Also, `LIKE` operations will be case insensitive and include the possibility of pagination.
<3> The database connection should be configured here.
<4> The `targetPackage` of the `javaModelGenerator` element is the package where the entity classes will be created. This value should match the `base-package` of the `mybatis:scan` element of the Spring configuration.
<5> The `targetPackage` of the `sqlMapGenerator` element is the package where the mapper files will be created. If not specified, the mapper files will be created in the package `mybatis.mappers` by default. This value should match the configuration value `persistence.mybatis.mapperLocations`.
<6> `tableName` contains an expression to select which tables and views of the database will be processed by the generator. Multiple `table` elements may appear if multiple expressions are to be used or different tables need different configurations

For further information about the configuration, refer to the documentation of http://www.mybatis.org/generator/[MyBatis Generator].

ifndef::getting-started[]
== Multiple databases

The <<cloud-altemistafwk-core-persistence-mybatis-conf-internals,MyBatis infrastructure provided by the {framework}>> does only support one single database (i.e.: one single _datasource_). However, it is possible to use multiple databases in {framework} applications by declaring an alternative infrastructure. Namely:

* A secondary JDBC `DataSource`.
* A new MyBatis `SqlSessionFactory` that uses the new data source and a different set of mapper locations.
* A new `MyBatisExceptionTranslator` that uses the new data source.
* A new `TransactionManager` that uses the new data source.

The services using the secondary data source must specify the new transaction manager:

[source]
----
@Transactional("altTransactionManager")
----
endif::getting-started[]
