
-- DEMO_TABLE values
insert into DEMO_TABLE (KEY, TINYINT_FIELD, INTEGER_FIELD) VALUES (1001, 1, 1);
insert into DEMO_TABLE (KEY, TINYINT_FIELD, INTEGER_FIELD) VALUES (1002, 1, 1);
insert into DEMO_TABLE (KEY, TINYINT_FIELD, INTEGER_FIELD) VALUES (1003, 1, 1);
insert into DEMO_TABLE (KEY, TINYINT_FIELD, INTEGER_FIELD) VALUES (1004, 1, 1);
insert into DEMO_TABLE (KEY, TINYINT_FIELD, INTEGER_FIELD) VALUES (1005, 1, 1);
insert into DEMO_TABLE (KEY, TINYINT_FIELD, INTEGER_FIELD) VALUES (1006, 1, 1);
insert into DEMO_TABLE (KEY, TINYINT_FIELD, INTEGER_FIELD) VALUES (1007, 1, 1);
insert into DEMO_TABLE (KEY, TINYINT_FIELD, INTEGER_FIELD) VALUES (1008, 1, 1);
insert into DEMO_TABLE (KEY, TINYINT_FIELD, INTEGER_FIELD) VALUES (1009, 1, 1);
insert into DEMO_TABLE (KEY, TINYINT_FIELD, INTEGER_FIELD) VALUES (1010, 1, 1);
