
:fragment:

This module allows processing large volumes of records.

A typical batch process generally reads a large number of records from a database, file, or queue, processes the data in some fashion, and then writes back data in a modified form. 

== Usage

`BatchService` is the main interface for the batch module:

[source]
----
@Autowired
private BatchService service;
----

This generic interface handles the following concepts:

* Job definitions, identified by their job names.

* Job instances, which represent a combination of a job definition with an identifying set of parameters.

* Job executions, which represent an attempt to run a job instance.

The definition of the job definitions depends on the implementation provider,
but will typically be located at the `jobs` package in the classpath (i.e.: `classpath:jobs/*`).

IMPORTANT: Only the following types can be parameters: String, Long, Date, and Double. {framework} BatchParameter implementations enforces the use of this type of parameters.

== Spring Batch-based implementation

The framework offers a Spring Batch based implementation for the Batch processing module.
With this implementation, jobs are defined as beans with an special namespace:

[source,xml]
.jobs/simple-job.xml
----
include::{basedir}/altemista-cloudfwk-core-batch-spring-conf/src/test/resources/jobs/test-jobs.xml[tags=simple]
----
<1> Use this namespace for defining the `<job>`, `<step>`, etc. beans.
<2> In Spring Batch, a job definition is composed of steps.
<3> The tasklet requires a transaction manager to work with.

For further and more detailed information about how the jobs and steps are defined,
please refer to the http://docs.spring.io/spring-batch/reference/html/configureJob.html[configuring (...) a job]
and http://docs.spring.io/spring-batch/reference/html/configureStep.html[configuring a step]
sections of the http://docs.spring.io/spring-batch/reference/html/index.html[Spring Batch Reference Documentation].
