package org.altemista.cloudfwk.remindersmybatis.module.model;

import java.io.Serializable;

public class RmndrsUsers implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMNDRS_USERS.USERNAME
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMNDRS_USERS.PASSWORD
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RMNDRS_USERS
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMNDRS_USERS.USERNAME
     *
     * @return the value of RMNDRS_USERS.USERNAME
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMNDRS_USERS.USERNAME
     *
     * @param username the value for RMNDRS_USERS.USERNAME
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMNDRS_USERS.PASSWORD
     *
     * @return the value of RMNDRS_USERS.PASSWORD
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMNDRS_USERS.PASSWORD
     *
     * @param password the value for RMNDRS_USERS.PASSWORD
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_USERS
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RmndrsUsers other = (RmndrsUsers) that;
        return (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_USERS
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_USERS
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", username=").append(username);
        sb.append(", password=").append(password);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}