package org.altemista.cloudfwk.remindersmybatis.module.model;

import java.io.Serializable;
import java.util.Date;

public class RmndrsTable implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMNDRS_TABLE.ID
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMNDRS_TABLE.USERNAME
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMNDRS_TABLE.TEXT
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    private String text;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMNDRS_TABLE.DUE_DATE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    private Date dueDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMNDRS_TABLE.COMPLETED
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    private Boolean completed;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RMNDRS_TABLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMNDRS_TABLE.ID
     *
     * @return the value of RMNDRS_TABLE.ID
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMNDRS_TABLE.ID
     *
     * @param id the value for RMNDRS_TABLE.ID
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMNDRS_TABLE.USERNAME
     *
     * @return the value of RMNDRS_TABLE.USERNAME
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMNDRS_TABLE.USERNAME
     *
     * @param username the value for RMNDRS_TABLE.USERNAME
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMNDRS_TABLE.TEXT
     *
     * @return the value of RMNDRS_TABLE.TEXT
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    public String getText() {
        return text;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMNDRS_TABLE.TEXT
     *
     * @param text the value for RMNDRS_TABLE.TEXT
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    public void setText(String text) {
        this.text = text == null ? null : text.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMNDRS_TABLE.DUE_DATE
     *
     * @return the value of RMNDRS_TABLE.DUE_DATE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    public Date getDueDate() {
        return dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMNDRS_TABLE.DUE_DATE
     *
     * @param dueDate the value for RMNDRS_TABLE.DUE_DATE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    public void setDueDate(Date dueDate) {
        this.dueDate = dueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMNDRS_TABLE.COMPLETED
     *
     * @return the value of RMNDRS_TABLE.COMPLETED
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    public Boolean getCompleted() {
        return completed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMNDRS_TABLE.COMPLETED
     *
     * @param completed the value for RMNDRS_TABLE.COMPLETED
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    public void setCompleted(Boolean completed) {
        this.completed = completed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_TABLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RmndrsTable other = (RmndrsTable) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getUsername() == null ? other.getUsername() == null : this.getUsername().equals(other.getUsername()))
            && (this.getText() == null ? other.getText() == null : this.getText().equals(other.getText()))
            && (this.getDueDate() == null ? other.getDueDate() == null : this.getDueDate().equals(other.getDueDate()))
            && (this.getCompleted() == null ? other.getCompleted() == null : this.getCompleted().equals(other.getCompleted()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_TABLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getUsername() == null) ? 0 : getUsername().hashCode());
        result = prime * result + ((getText() == null) ? 0 : getText().hashCode());
        result = prime * result + ((getDueDate() == null) ? 0 : getDueDate().hashCode());
        result = prime * result + ((getCompleted() == null) ? 0 : getCompleted().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_TABLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", username=").append(username);
        sb.append(", text=").append(text);
        sb.append(", dueDate=").append(dueDate);
        sb.append(", completed=").append(completed);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}