package org.altemista.cloudfwk.remindersmybatis.module.model;

import java.io.Serializable;

public class RmndrsRoles implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMNDRS_ROLES.ID
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column RMNDRS_ROLES.ROLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table RMNDRS_ROLES
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMNDRS_ROLES.ID
     *
     * @return the value of RMNDRS_ROLES.ID
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMNDRS_ROLES.ID
     *
     * @param id the value for RMNDRS_ROLES.ID
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column RMNDRS_ROLES.ROLE
     *
     * @return the value of RMNDRS_ROLES.ROLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column RMNDRS_ROLES.ROLE
     *
     * @param role the value for RMNDRS_ROLES.ROLE
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_ROLES
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RmndrsRoles other = (RmndrsRoles) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getRole() == null ? other.getRole() == null : this.getRole().equals(other.getRole()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_ROLES
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getRole() == null) ? 0 : getRole().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_ROLES
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", role=").append(role);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}