
:fragment:

===== Entity DTO
[source,java,linenums]
./AltemistaMoviesRecommendations-client/src/main/java/org/altemista/cloudfwk/demo/altemistamoviesrecomend/microservice/domain/RecommendationDTO.java
----
public class RecommendationDTO {
	
	Long id;
	private Long userId;
	private String userFirstName;
	private String userLastName;
	private Long movieId;
	private String movieTitle;
	private String comment;

	<1>	
}
----
<1> Getters and setters

===== Microservice interface

First of all you have to rename the `MicroserviceExample` class. The new name will be `AltemistaMoviesRecommendations`.

[[recommendations-interface]]
[source,java,linenums]
.AltemistaMoviesRecommendations.java
----
package org.altemista.cloudfwk.demo.altemistamoviesrecomend.microservice.service;

import java.util.List;

import org.springframework.cloud.netflix.feign.FeignClient;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.altemista.cloudfwk.demo.altemistamoviesrecomend.microservice.domain.RecommendationDTO;

@FeignClient("AltemistaMoviesRecommendations")
public interface AltemistaMoviesRecommendations {

	@RequestMapping(value = "/", method = RequestMethod.GET)
	ResponseEntity<List<RecommendationDTO>> listAllRecommendations(); // <1>

	@RequestMapping(value = "/{id}", method = RequestMethod.GET)
	ResponseEntity<RecommendationDTO> getRecommendation(@PathVariable("id") long id); // <2>

	@RequestMapping(value = "/", method = RequestMethod.POST)
	ResponseEntity<RecommendationDTO> createRecommendation(
		@RequestBody RecommendationDTO recommendationDTO); // <3>

	@RequestMapping(value = "/{id}", method = RequestMethod.PUT)
	ResponseEntity<RecommendationDTO> updateRecommendation(@PathVariable("id") long id, 
		@RequestBody RecommendationDTO recommendationDTO); // <4>

	@RequestMapping(value = "/{id}", method = RequestMethod.DELETE)
	ResponseEntity<RecommendationDTO> deleteRecommendation(@PathVariable("id") long id); // <5>

	@RequestMapping(value = "/findByUserID/{userId}", method = RequestMethod.GET)
	ResponseEntity<List<RecommendationDTO>> findByUserID(@PathVariable("userId") Long userId); // <6>

}
----

<1> This method gets all Recommendations.
<2> This method gets a Recommendation by ID.
<3> This method creates a Recommendation.
<4> This method updates a Recommendation.
<5> This method deletes a Recommendation.
<6> This method gets all Recommendations by User ID.

IMPORTANT: You can delete the example classes generated by the archetype like `MicroserviceExampleRequest` and `MicroserviceExampleResponse`. 