:fragment:

In this example we will create a ACF Thymeleaf web application.

We will add initial business module stand-alone-implementation.

Over the webapp project add a new "ALTEMISTA Cloud Framework (ACF) Feature" and choose the "Thymeleaf".

==== Thymeleaf Template

*Thymeleaf Template* is a template file. Its contents are in the XML/XHTML/HTML5 format. We will create 3 files and place it in the  webapp/WEB-INF/templates ​​​​​​​folder:


[source,html,options="nowrap"]
./templates/index.html
----
<!DOCTYPE HTML>
<html xmlns:th="http://www.thymeleaf.org">
   <head>
      <meta charset="UTF-8" />
      <title>Welcome</title>
      <link rel="stylesheet" type="text/css" th:href="@{/style.css}"/>
   </head>
   <body>
      <h1>Welcome</h1>
      <h2 th:utext="${message}">..!..</h2>
          
      <a th:href="@{/employeeList}">Employee List</a>  
       
   </body>
    
</html>
----

[source,html,options="nowrap"]
./templates/addEmployee.html
----
<!DOCTYPE HTML>
<html xmlns:th="http://www.thymeleaf.org">
   <head>
      <meta charset="UTF-8" />
      <title>Add Employee</title>
      <link rel="stylesheet" type="text/css" th:href="@{/style.css}"/>
      <script th:inline="javascript">
      function myFunction(field1, field2)
      {
    	  var fieldActive1 = document.getElementById(field1);
    	  var fieldActive2 = document.getElementById(field2);
    	  if(fieldActive1.checked == true){
    	  	fieldActive2.disabled = true;
    	  }else{
    		  fieldActive2.disabled = false;
    	  }
    	  if(fieldActive2.checked == true){
      	  	fieldActive1.disabled = true;
      	  }else{
      		  fieldActive1.disabled = false;
      	  }
    	  
      }
</script>
   </head>
   <body>
      <h1>Create an Employee:</h1>
       
      <!--  
         In Thymeleaf the equivalent of
         JSP's ${pageContext.request.contextPath}/edit.html
         would be @{/edit.html}         
         -->
          
      <form th:action="@{/addEmployee}"
         th:object="${employeeForm}" method="POST">
         First Name:
         <input type="text" th:field="*{name}" />    
         <br/><br/>
         Last Name:
         <input type="text" th:field="*{surname}" />     
         <br/><br/>
         Gender:
         <select th:field="*{gender}">
    		<option th:value="'M'" th:text="Male"></option>
    		<option th:value="'F'" th:text="Female"></option>
		 </select>
         <br/><br/>
         Proyect Manager
         <input type="checkbox" th:field="*{position}" th:name="P" th:value="1" th:onclick="'myFunction(\'position2\',\'position1\');'"/>
         Developer
         <input type="checkbox" th:field="*{position}" th:name="D" th:value="2" th:onclick="'myFunction(\'position1\',\'position2\');'"/>
         <br/><br/>
         <input type="submit" value="Create" />
      </form>
       
      <br/>
       
      <!-- Check if errorMessage is not null and not empty -->
       
      <div th:if="${errorMessage}" th:utext="${errorMessage}"
         style="color:red;font-style:italic;">
         ...
      </div>
       
   </body>
</html>
----

[source,html,options="nowrap"]
./templates/employeeList.html
----
<!DOCTYPE HTML>
<html xmlns:th="http://www.thymeleaf.org">
   <head>
      <meta charset="UTF-8" />
      <title>Employee List</title>
      <link rel="stylesheet" type="text/css" th:href="@{style.css}"/>
   </head>
   <body>
      <h1>Employee List</h1>
      <a href="addEmployee">Add Employee</a>
      <br/><br/>
      <div>
         <table border="1">
            <tr>
               <th>First Name</th>
               <th>Last Name</th>
               <th>Gender</th>
               <th>Position</th>
            </tr>
            <tr th:each ="employee : ${employees}">
               <td th:utext="${employee.name}">...</td>
               <td th:utext="${employee.surname}">...</td>
               <td> 
               		<span th:if="${employee.gender == 'M'}" > Male</span>
               		<span th:unless="${employee.gender == 'M'}">Female</span>
			   	</td>
				<td th:switch="${employee.position}">
   					<span th:case="'1'" th:text=" 'Project Manager'" /> 
    				<span th:case="'2'" th:text=" 'Developer'" />
				</td>
            </tr>
         </table>
      </div>
   </body>
</html>
----
For Static Resources, for example, css, javascript, image files,.. you need to put them into webapp/WEB-INF/resources/ folder or its subfolders.
[source,css,options="nowrap"]
./resources/style.css
----
h1 {
    color:#0000FF;
}
 
h2 {
    color:#FF0000;
}
 
table {
    border-collapse: collapse;
}
 
table th, table td {
    padding: 5px;
}
----

==== Model, Form, Controller classes


[source,java,options="nowrap"]
./.com.mycompany.application.module.model.Employee
----
package com.mycompany.application.module.model;

public class Employee {
	
	private String name;
	
	private String surname;
	
	private String gender;
	
	private String position;
	
	public Employee(String name, String surname, String gender, String position){
		
		this.name= name;
		this.surname = surname;
		this.gender = gender;
		this.position = position;
		
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getPosition() {
		return position;
	}

	public void setPosition(String position) {
		this.position = position;
	}
	

}
----

EmployeeForm class  represents for the data of   FORM when you create a new employee on addEmployee page..

[source,java,options="nowrap"]
./com.mycompany.application.module.form.EmployeeForm
----
package com.mycompany.application.module.form;

public class EmployeeForm {
	
	private String name;
	
	private String surname;
	
	private String gender;
	
	private String position;

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}
	
	public String getPosition() {
		return position;
	}

	public void setPosition(String position) {
		this.position = position;
	}
	
}

----

EmployeeController is a controller class. It processes a user's requests and controls the flow of the application.

//
[source,java,linenums]
./src/main/java/com/application/module/controller
----
package com.mycompany.application.module.controller;

import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import com.mycompany.application.module.form.EmployeeForm;
import com.mycompany.application.module.model.Employee;

@Controller
public class EmployeeController
{
    
    @Value("${welcome.message}")
    private String message;
 
    @Value("${error.message}")
    private String errorMessage;
    
    private static List<Employee> employees = new ArrayList<Employee>();
    
    static {
    	employees.add(new Employee("Bill", "Gates", "M","1"));
    	employees.add(new Employee("Marie", "Curie", "F", "2"));
    }
    
    @RequestMapping(value = { "/", "/index" }, method = RequestMethod.GET)
    public String index(Model model) {
 
        model.addAttribute("message", message);
 
        return "index";
    }


    @RequestMapping(value = { "/employeeList" }, method = RequestMethod.GET)
    public String employeeList(Model model) {
    	
        model.addAttribute("employees", employees);
 
        return "employeeList";
    }
 
    @RequestMapping(value = { "/addEmployee" }, method = RequestMethod.GET)
    public String showAddEmployeePage(Model model) {
 
        EmployeeForm employeeForm = new EmployeeForm();
        model.addAttribute("employeeForm", employeeForm);
 
        return "addEmployee";
    }
 
    @RequestMapping(value = { "/addEmployee" }, method = RequestMethod.POST)
    public String saveEmployee(Model model, //
            @ModelAttribute("employeeForm") EmployeeForm employeeForm) {
 
        String firstName = employeeForm.getName();
        String lastName = employeeForm.getSurname();
        String gender = employeeForm.getGender();
        String position = employeeForm.getPosition();
 
        if (firstName != null && firstName.length() > 0 //
                && lastName != null && lastName.length() > 0
        	&& position != null && position.length() > 0) {
            Employee newEmployee = new Employee(firstName, lastName, gender, position);
            employees.add(newEmployee);
 
            return "redirect:/employeeList";
        }
 
        model.addAttribute("errorMessage", errorMessage);
        return "addEmployee";
    }
}

----

And finally add the property messages.
//
[source,properties]
./src/main/resources/config/properties/new-application-thy.properties
----
*.welcome.message=Hello Thymeleaf
*.error.message=First Name & Last Name & Gender & Position is required!
----

==== Test our application

Run your application using any web server you want and the application should have been deployed in "http://localhost:8080/new-application-thy-webapp/"

