
:fragment:

The {framework} https://projects.spring.io/spring-boot/[Spring Boot] nature is an application nature that allows the creation of stand-alone Spring based applications.

This nature is intended to be a drop-in replacement of the web application nature, and therefore aims to provide the same default features: bootstrapping the {framework} Spring context in Spring Web MVC and serving static resources. However, it actually uses a slightly different configuration and does not natively support the presentation layer modules (such as Apache Tiles or JavaServer Faces).

== Presentation layer implementation

This module uses the default Spring Boot configuration, meaning the Spring context is bootstrapped as the `/*` mapping and static resources are directly served from the classpath (at `/META-INF/resources`, `/resources`, `/static` and `/public`). Hence, this default configuration serves:

* Spring MVC *controllers* at `/*`. This ``@Controller``s can be in the Spring Boot aggregator project or in any of the web projects of the application.

* *Static resources* at `/*` (when the URI is not matched by any controller), from both theSpring Boot aggregator project directly or from the classpath, from any of the default folders (`/META-INF/resources`, `/resources`, `/static` and `/public`).

[TIP]
====
If static resources are to be declared in business modules, prefer the `/META-INF/resources` folder because these resources will also be served if the business module is included in a {framework} web application, whether resources in `/resources`, `/static` or `/public` will not (at least, with the default {framework} configuration).

Consider creating a separate <<applications-business-module-types,stand-alone web part>> to hold the presentation layer for compatibility with, and portability to, {framework} web applications.
====
