
-- DEMO_TABLE values
INSERT INTO DEMO_TABLE (KEY,
	INTEGER_FIELD, INT_FIELD, SMALLINT_FIELD, TINYINT_FIELD, BIGINT_FIELD,
	DECIMAL_FIELD, NUMERIC_FIELD, FLOAT_FIELD, DOUBLE_FIELD,
	DATE_FIELD, DATETIME_FIELD, TIMESTAMP_FIELD, TIME_FIELD,
	CHAR_FIELD, VARCHAR_FIELD, BINARY_FIELD, VARBINARY_FIELD,
	BLOB_FIELD
	
) VALUES (1001,
	NULL, NULL, NULL, NULL, NULL,
	NULL, NULL, NULL, NULL,
	NULL, NULL, NULL, NULL,
	NULL, NULL, NULL, NULL,
	NULL
);

INSERT INTO DEMO_TABLE (KEY,
	INTEGER_FIELD, INT_FIELD, SMALLINT_FIELD, TINYINT_FIELD, BIGINT_FIELD,
	DECIMAL_FIELD, NUMERIC_FIELD, FLOAT_FIELD, DOUBLE_FIELD,
	DATE_FIELD, DATETIME_FIELD, TIMESTAMP_FIELD, TIME_FIELD,
	CHAR_FIELD, VARCHAR_FIELD, BINARY_FIELD, VARBINARY_FIELD,
	BLOB_FIELD
	
) VALUES (1002,
	1, 2, 3, 4, 5,
	6, 7, 8.9, 10.11,
	NOW(), NOW(), NOW(), NOW(),
	'foo', 'bar', '62617a', '717578',
	'71757578'
);

INSERT INTO DEMO_TABLE (KEY,
	INTEGER_FIELD, INT_FIELD, SMALLINT_FIELD, TINYINT_FIELD, BIGINT_FIELD,
	DECIMAL_FIELD, NUMERIC_FIELD, FLOAT_FIELD, DOUBLE_FIELD,
	DATE_FIELD, DATETIME_FIELD, TIMESTAMP_FIELD, TIME_FIELD,
	CHAR_FIELD, VARCHAR_FIELD, BINARY_FIELD, VARBINARY_FIELD,
	BLOB_FIELD
	
) VALUES (1003,
	NULL, NULL, NULL, NULL, NULL,
	NULL, NULL, NULL, NULL,
	NULL, NULL, NULL, NULL,
	NULL, NULL, NULL, NULL,
	NULL
);
