
:fragment:

== Core performance

For the core performance feature to start measuring the method execution times, declare the next aspect at the application level:

[source,xml]
.spring/new-application-performance.xml
----
include::{basedir}/cloud-altemistafwk-app-performance-conf/src/test/resources/spring/cloud-altemistafwk-example-performance.xml[tags=methodExecutionPerformanceAspect]
----
<1> The `methodExecutionPerformanceAspect` bean is already provided in the framework.
<2> This is just an example; use the pointcut that best suits your needs.

== JDBC performance

For the JDBC performance feature to start measuring the queries execution times, wrap the data source to be measured and use the wrapped data source in your application:

[source,xml]
.spring/new-application-performance.xml
----
include::{basedir}/cloud-altemistafwk-app-performance-jdbc-conf/src/test/resources/spring/cloud-altemistafwk-example-performance-jdbc.xml[tags=jdbcPerformance]
----
<1> Use the actual data source as the first constructor argument. If more than one data source is to be measured, create different wrapper instances.
<2> The `jdbcMeasuredTaskHolder` bean is already provided by the framework.
<3> A `jdbcMeasuresStorage` bean is also provided by the framework.
<4> The optional `executionTracePattern` argument is the pattern to match the execution point. If provided, the signature of the method that invoked the JDBC operation will be stored along the operation using `MatchUtil.stackTraceElementMatching(String)`.

== Web performance

The web performance feature does not require any configuration to start measuring request execution times.

TIP: An interesting, and usually desired, configuration is to combine the web request information with the method execution information. This can be achieved by overriding some the <<cloud-altemistafwk-app-performance-conf-internals-web,default configuration>> of the feature.
