
:fragment:

For the servlet part, the _web fragment_ of the {framework} security feature set authentication user name of Spring Security in MDC, as described in http://terasolunaorg.github.io/guideline/5.2.0.RELEASE/en/ArchitectureInDetail/GeneralFuncDetail/Logging.html#setting-value-in-mdc-using-filter[TERASOLUNA Server Framework Development Guideline]:

[source,xml,options="nowrap"]
.altemista-cloudfwk-web-security-conf/src/main/resources/META-INF/web-fragment.xml
----
include::{basedir}/altemista-cloudfwk-web-security-conf/src/main/resources/META-INF/web-fragment.xml[tags=internals]
----

For reference (and ordering purposes if required), this web fragment is named `altemistaCloudWebSecurity` and is loaded after `altemistaCloudWebappSecurity`:
[source,xml,options="nowrap"]
.altemista-cloudfwk-app-security-conf/src/main/resources/META-INF/web-fragment.xml
----
include::{basedir}/altemista-cloudfwk-web-security-conf/src/main/resources/META-INF/web-fragment.xml[tags=name]
----

NOTE: This configuration is mirrored in `org.altemista.cloudfwk.config.boot.WebSecurityConfig` for Spring Boot-based applications.

This configuration effectively relies on Spring beans:

[source,xml,options="nowrap"]
.org/altemista/cloudfwk/config/web/altemista-cloudfwk-web-security.xml
----
include::{basedir}/altemista-cloudfwk-web-security-conf/src/main/resources/org/altemista/cloudfwk/config/web/altemista-cloudfwk-web-security.xml[tags=internals]
----

The _forwarding credentials_ feature is set up as follows:

[source,xml,options="nowrap"]
.org/altemista/cloudfwk/config/web/altemista-cloudfwk-web-security.xml
----
include::{basedir}/altemista-cloudfwk-web-security-conf/src/main/resources/org/altemista/cloudfwk/config/web/altemista-cloudfwk-web-security.xml[tags=forward]
----
