
:fragment:

To bootstrap and launch the Microservice-based {framework} application, implements the `cloud.altemista.fwk.config.microservice.CloudAltemistafwkMicroserviceBuilder` and call the _configureApplication_ method as follows:

[source]
.com.mycompany.application.microservice.MicroserviceApplication.java
----
@CloudAltemistafwkMicroservice
public class MicroserviceApplication extends CloudAltemistafwkMicroserviceBuilder {
    public static void main(String[] args) {
        configureApplication(new CloudAltemistafwkApplicationBuilder(), MicroserviceApplication.class).run(args);
    }
}
----

This configureApplication method creates and runs a Microservice-based {framework} application (`cloud.altemista.fwk.config.boot.CloudAltemistafwkApplication`) like a Spring Boot-based application using the following configuration:

* Add the {framework} initializers to the application before the {framework} Spring context gets loaded.

* Uses the default Spring Boot configuration wherever possible.

 ** Imports the <<natures-core-internals,_core_ configuration of the framework>> first. All the features that are not dependent on the deployment platform will be loaded at this point.

* Includes all the Microservice-based application features found in the classpath, by importing their configuration classes (that will be under the package `cloud.altemista.fwk.config.microservice`).

* Imports the application configuration files, located at `spring/*.xml` in the classpath.

The {framework} `@CloudAltemistafwkMicroservice` annotate the main class with the `@EnableEurekaClient` and with a `@ComponentScan` over the same package as that annotation class.

[source,java]
----
include::{basedir}/cloud-altemistafwk-microservice-conf/src/main/java/cloud/altemista/fwk/config/microservice/CloudAltemistafwkMicroservice.java[tags=annotation]
----
<1> `@ComponentScan` over the same package as the `@CloudAltemistafwkMicroservice` class.
<2> `@EnableEurekaClient` annotation to enable the application as Eureka Client

IMPORTANT: If the application has to be instantiate in a Eureka Server, the `spring.cloud.discovery.enabled` property will be set true.