package com.mycompany.application.module.model;

/*
 * #%L
 * altemista-cloud persistence: MyBatis integration tests
 * %%
 * Copyright (C) 2017 NTT DATA Corporation
 * %%
 * All rights reserved.
 * Todos los derechos reservados.
 * #L%
 */


import java.util.ArrayList;
import java.util.List;

public class DemoTableExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    public DemoTableExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andKeyIsNull() {
            addCriterion("KEY is null");
            return (Criteria) this;
        }

        public Criteria andKeyIsNotNull() {
            addCriterion("KEY is not null");
            return (Criteria) this;
        }

        public Criteria andKeyEqualTo(Integer value) {
            addCriterion("KEY =", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyNotEqualTo(Integer value) {
            addCriterion("KEY <>", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyGreaterThan(Integer value) {
            addCriterion("KEY >", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyGreaterThanOrEqualTo(Integer value) {
            addCriterion("KEY >=", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyLessThan(Integer value) {
            addCriterion("KEY <", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyLessThanOrEqualTo(Integer value) {
            addCriterion("KEY <=", value, "key");
            return (Criteria) this;
        }

        public Criteria andKeyIn(List<Integer> values) {
            addCriterion("KEY in", values, "key");
            return (Criteria) this;
        }

        public Criteria andKeyNotIn(List<Integer> values) {
            addCriterion("KEY not in", values, "key");
            return (Criteria) this;
        }

        public Criteria andKeyBetween(Integer value1, Integer value2) {
            addCriterion("KEY between", value1, value2, "key");
            return (Criteria) this;
        }

        public Criteria andKeyNotBetween(Integer value1, Integer value2) {
            addCriterion("KEY not between", value1, value2, "key");
            return (Criteria) this;
        }

        public Criteria andTinyintFieldIsNull() {
            addCriterion("TINYINT_FIELD is null");
            return (Criteria) this;
        }

        public Criteria andTinyintFieldIsNotNull() {
            addCriterion("TINYINT_FIELD is not null");
            return (Criteria) this;
        }

        public Criteria andTinyintFieldEqualTo(Byte value) {
            addCriterion("TINYINT_FIELD =", value, "tinyintField");
            return (Criteria) this;
        }

        public Criteria andTinyintFieldNotEqualTo(Byte value) {
            addCriterion("TINYINT_FIELD <>", value, "tinyintField");
            return (Criteria) this;
        }

        public Criteria andTinyintFieldGreaterThan(Byte value) {
            addCriterion("TINYINT_FIELD >", value, "tinyintField");
            return (Criteria) this;
        }

        public Criteria andTinyintFieldGreaterThanOrEqualTo(Byte value) {
            addCriterion("TINYINT_FIELD >=", value, "tinyintField");
            return (Criteria) this;
        }

        public Criteria andTinyintFieldLessThan(Byte value) {
            addCriterion("TINYINT_FIELD <", value, "tinyintField");
            return (Criteria) this;
        }

        public Criteria andTinyintFieldLessThanOrEqualTo(Byte value) {
            addCriterion("TINYINT_FIELD <=", value, "tinyintField");
            return (Criteria) this;
        }

        public Criteria andTinyintFieldIn(List<Byte> values) {
            addCriterion("TINYINT_FIELD in", values, "tinyintField");
            return (Criteria) this;
        }

        public Criteria andTinyintFieldNotIn(List<Byte> values) {
            addCriterion("TINYINT_FIELD not in", values, "tinyintField");
            return (Criteria) this;
        }

        public Criteria andTinyintFieldBetween(Byte value1, Byte value2) {
            addCriterion("TINYINT_FIELD between", value1, value2, "tinyintField");
            return (Criteria) this;
        }

        public Criteria andTinyintFieldNotBetween(Byte value1, Byte value2) {
            addCriterion("TINYINT_FIELD not between", value1, value2, "tinyintField");
            return (Criteria) this;
        }

        public Criteria andIntegerFieldIsNull() {
            addCriterion("INTEGER_FIELD is null");
            return (Criteria) this;
        }

        public Criteria andIntegerFieldIsNotNull() {
            addCriterion("INTEGER_FIELD is not null");
            return (Criteria) this;
        }

        public Criteria andIntegerFieldEqualTo(Integer value) {
            addCriterion("INTEGER_FIELD =", value, "integerField");
            return (Criteria) this;
        }

        public Criteria andIntegerFieldNotEqualTo(Integer value) {
            addCriterion("INTEGER_FIELD <>", value, "integerField");
            return (Criteria) this;
        }

        public Criteria andIntegerFieldGreaterThan(Integer value) {
            addCriterion("INTEGER_FIELD >", value, "integerField");
            return (Criteria) this;
        }

        public Criteria andIntegerFieldGreaterThanOrEqualTo(Integer value) {
            addCriterion("INTEGER_FIELD >=", value, "integerField");
            return (Criteria) this;
        }

        public Criteria andIntegerFieldLessThan(Integer value) {
            addCriterion("INTEGER_FIELD <", value, "integerField");
            return (Criteria) this;
        }

        public Criteria andIntegerFieldLessThanOrEqualTo(Integer value) {
            addCriterion("INTEGER_FIELD <=", value, "integerField");
            return (Criteria) this;
        }

        public Criteria andIntegerFieldIn(List<Integer> values) {
            addCriterion("INTEGER_FIELD in", values, "integerField");
            return (Criteria) this;
        }

        public Criteria andIntegerFieldNotIn(List<Integer> values) {
            addCriterion("INTEGER_FIELD not in", values, "integerField");
            return (Criteria) this;
        }

        public Criteria andIntegerFieldBetween(Integer value1, Integer value2) {
            addCriterion("INTEGER_FIELD between", value1, value2, "integerField");
            return (Criteria) this;
        }

        public Criteria andIntegerFieldNotBetween(Integer value1, Integer value2) {
            addCriterion("INTEGER_FIELD not between", value1, value2, "integerField");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated do_not_delete_during_merge Wed Apr 27 19:14:46 CEST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}
