package com.mycompany.application.module.model;

/*
 * #%L
 * altemista-cloud persistence: MyBatis integration tests
 * %%
 * Copyright (C) 2017 NTT DATA Corporation
 * %%
 * All rights reserved.
 * Todos los derechos reservados.
 * #L%
 */


import java.io.Serializable;

import com.mycompany.application.module.model.DemoTable;

public class DemoTable implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEMO_TABLE.KEY
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    private Integer key;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEMO_TABLE.TINYINT_FIELD
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    private Byte tinyintField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEMO_TABLE.INTEGER_FIELD
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    private Integer integerField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEMO_TABLE.KEY
     *
     * @return the value of DEMO_TABLE.KEY
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    public Integer getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEMO_TABLE.KEY
     *
     * @param key the value for DEMO_TABLE.KEY
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    public void setKey(Integer key) {
        this.key = key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEMO_TABLE.TINYINT_FIELD
     *
     * @return the value of DEMO_TABLE.TINYINT_FIELD
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    public Byte getTinyintField() {
        return tinyintField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEMO_TABLE.TINYINT_FIELD
     *
     * @param tinyintField the value for DEMO_TABLE.TINYINT_FIELD
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    public void setTinyintField(Byte tinyintField) {
        this.tinyintField = tinyintField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEMO_TABLE.INTEGER_FIELD
     *
     * @return the value of DEMO_TABLE.INTEGER_FIELD
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    public Integer getIntegerField() {
        return integerField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEMO_TABLE.INTEGER_FIELD
     *
     * @param integerField the value for DEMO_TABLE.INTEGER_FIELD
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    public void setIntegerField(Integer integerField) {
        this.integerField = integerField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DemoTable other = (DemoTable) that;
        return (this.getKey() == null ? other.getKey() == null : this.getKey().equals(other.getKey()))
            && (this.getTinyintField() == null ? other.getTinyintField() == null : this.getTinyintField().equals(other.getTinyintField()))
            && (this.getIntegerField() == null ? other.getIntegerField() == null : this.getIntegerField().equals(other.getIntegerField()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getKey() == null) ? 0 : getKey().hashCode());
        result = prime * result + ((getTinyintField() == null) ? 0 : getTinyintField().hashCode());
        result = prime * result + ((getIntegerField() == null) ? 0 : getIntegerField().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Wed Apr 27 19:14:46 CEST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", key=").append(key);
        sb.append(", tinyintField=").append(tinyintField);
        sb.append(", integerField=").append(integerField);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
