
:fragment:

The JavaServer Faces module can be added to {framework} projects with the webapp nature.

The provided implementation is http://www.primefaces.org/[PrimeFaces].

This feature sets up the following configuration:

* `{asterisk}.jsf` is used as the URL pattern for mapping of the Faces Servlet, `{asterisk}.xhtml` as the default suffix for the pages and the access to the raw XHTML documents is forbidden.

* A custom `ResourceHandler` implementation (actually, a custom `PrimeResourceHandler` implementation) is provided to work around a limitation of JSF when the Faces Servlet is not processing the request but another MVC technology (such as Spring Web Flow) is.
////
* To favor modularity, a `ResourceResolver` is provided that allows the XHTML documents to be in the WEB-INF folder and also in the META-INF folder of any jar in the classpath. Depending on the internal path of the resource:

	** `/WEB-INF/<path>`: will be treated first as an internal path but, if not found, will retry looking for the resource `META-INF/<path>` in the claspath.
	** `/META-INF/<path>`: will directly look for the resource `META-INF/<path>` in the claspath.
	** Any other path will be treated as an internal path.
////

Each application should have its own `faces-config.xml` (or multiple files ending in `.faces-config.xml` in the META-INF directory in the classpath) where the application views and managed beans will be declared as shown in the example:

[source,xml]
.WEB-INF/faces-config.xml
----
<?xml version='1.0' encoding='UTF-8'?>
<faces-config xmlns="http://java.sun.com/xml/ns/javaee"
		xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		xsi:schemaLocation="http://java.sun.com/xml/ns/javaee
		http://java.sun.com/xml/ns/javaee/web-facesconfig_2_0.xsd"
		version="2.0">

	<navigation-rule>
		<from-view-id>*</from-view-id>

		<navigation-case>
			<from-outcome>home</from-outcome>
			<to-view-id>/welcome-page.xhtml</to-view-id>
		</navigation-case>

	</navigation-rule>

</faces-config>
----

Welcome and error pages can be configured in `web.xml` as in any other web application:

[source,xml]
.WEB-INF/web.xml
----
<?xml version="1.0" encoding="UTF-8"?>
<web-app version="3.0"
	xmlns="http://java.sun.com/xml/ns/javaee"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:web="http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd"
	xsi:schemaLocation="http://java.sun.com/xml/ns/javaee http://java.sun.com/xml/ns/javaee/web-app_3_0.xsd">

	<display-name>Example JSF application</display-name>

	<welcome-file-list>
		<welcome-file>/welcome-page.jsf</welcome-file><!--1-->
	</welcome-file-list>

	<error-page>
		<error-code>500</error-code><!--2-->
		<location>/global-error-page.jsf</location><!--3-->
	</error-page>
	<error-page>
		<exception-type>com.example.ExampleApplicationException</exception-type><!--2-->
		<location>/custom-error-page.jsf</location><!--3-->
	</error-page>

</web-app>
----
<1> The welcome page is usually a plain static HTML or a JSP, but can also be rendered by JSF
<2> Error pages can be mapped to error codes or exception types
<3> As the welcome page, error pages can also be rendered by JSF
