
:fragment:

This modules provides a configured servlet as follows:

[source,xml,options="nowrap"]
.altemista-cloudfwk-webapp-jsf-conf/src/main/resources/META-INF/web-fragment.xml
----
include::{basedir}/altemista-cloudfwk-webapp-jsf-conf/src/main/resources/META-INF/web-fragment.xml[tags=internals]
----

For reference (and ordering purposes if required), this web fragment is named `altemistaCloudWebappPrimefaces`.

As you can see in the previous fragment, we are including `/WEB-INF/springsecurity.taglib.xml` which allows the use of
the Spring Security Facelets Tag Library. The content of this file is:

[source,xml,options="nowrap"]
.altemista-cloudfwk-webapp-jsf-conf/src/main/resources/META-INF/springsecurity.taglib.xml
----
include::{basedir}/altemista-cloudfwk-webapp-jsf-conf/src/main/resources/META-INF/springsecurity.taglib.xml[tags=internals]
----

In addition, the module configures some other required elements which are nececesary to work properly with the internationalization provided by the
framework and delegates to the Spring context resolving name references to Spring-defined beans.

[source,xml,options="nowrap"]
.altemista-cloudfwk-webapp-jsf-conf/src/main/resources/META-INF/faces-config.xml
----
include::{basedir}/altemista-cloudfwk-webapp-jsf-conf/src/main/resources/META-INF/faces-config.xml[tags=internals]
----
