
-- DROP tables if exists
DROP TABLE T_PROPERTIES IF EXISTS;

--
-- Table structure for table T_PROPERTIES
--
CREATE TABLE T_PROPERTIES (ID INTEGER IDENTITY PRIMARY KEY, KEY VARCHAR(250) NOT NULL, VALUE VARCHAR(250) NOT NULL, UNIQUE(KEY));
