
:fragment:

The main point of configuration of the business rules management feature is to define the available rule sets, and where they are actually stored.

Regardless of the implementation provider, a convenience base class `AbstractRulesServiceImpl` that implements `RulesetService` interface is provided by the framework.

This class uses a `RulesetContainerResolver` to translate the logical name of the rule set (used by the application) to `RulesetContainer` beans. This containers will be used by the `RulesetService` implementations to ultimately access the required rule set.

Currently, there are two `RulesetContainerResolver` implementations included in the module:

* `SimpleRulesetContainerResolverImpl`, returning always the same `RulesetContainer` (i.e.: this implementation ignores the logical name of the rule set).

* `NameBasedRulesetContainerResolverImpl`, that maps rule set identifiers to `RulesetContainer` instances, and allows a fallback `RulesetContainer` when no matches are found.

An application can override the `rulesetContainerResolver` bean with any onther implementation of `RulesetContainerResolver` as follows:

[source,xml]
.spring/my-application-rules-env.xml
----
<bean id="rulesetContainerResolver"
		class="cloud.altemista.fwk.core.rules.ruleset.impl.NameBasedRulesetContainerResolverImpl">
	<constructor-arg>
		<map>
			<entry key="accounts" value-ref="specialRulesetContainer" /> <!--1-->
			<entry key="users" value-ref="specialRulesetContainer" /> <!--2-->
		</map>
	</constructor-arg>

	<property name="fallbackRulesetResolver" ref="..." /> <!--3-->
</bean>
----
<1> When the rule set requested is `accounts`, the container will be resolved by the `specialRulesetContainer` bean (not shown in the example).
<2> More than one rule set can be mapped to the same container. In this example, both `accounts` and `users` rule sets are contained in the `specialRulesetContainer`.
<3> For any other rule set name, the fallback container will be used.

IMPORTANT: When using a `NameBasedRulesetContainerResolverImpl` the default container returned by `getDefaultRulesetContainer()` is not necessarily the fallback container, but the first container in the map whose `isDefaultContainer()` flag is active.

== Drools-based implementation

The default configuration of the Drools-based implementation only requires the definition of a `KieModule` in the classpath. Namely, the module requires a `META-INF/kmodule.xml` file in the root of the classpath (e.g.: `src/main/resources`).

The minimal `kmodule.xml` file is as follows:

[source,xml]
.META-INF/kmodule.xml
----
include::{basedir}/cloud-altemistafwk-core-rules-drools-conf/src/test/resources/META-INF/kmodule.xml[]
----
<1> An empty `kmodule` will actually find and load all the rules in the classpath (i.e.: all the DRL files)

=== Rule set containers

The Drools-based implementation includes some `RulesetContainer` implementations:

`DefaultDroolsRulesetContainerImpl`::

This implementation creates the `KieModule` from the classpath root. It is the one used in the aforementioned default configuration.

`DroolsUrlRulesetContainerImpl`::

A `DroolsUrlRulesetContainerImpl` can build the `KieModule` for a variety of sources denoted by an URL. +
If the URL starts with `classpath:`, the module will be laoded from the classpath. By example, if the URL is `classpath:ruleset/accounts`, the file `classpath:ruleset/accounts/META-INF/kmodule.xml` will be read as the module definition. +
If the URL starts with `file:`, the module will be loaded from the file system. By example, if the URL is `file:///rulesets/accounts`, the module definition is expected to be in the filesystem at the location `/ruleset/accounts/META-INF/kmodule.xml`. +
Otherwise, the module definition will be read from a remote location. In this case, and if authentication is required, there are three properties that can be set in the bean: `username` and `password`, and the boolean flag `basicAuthentication`.

`DroolsRepositoryRulesetContainerImpl`::

This implementation can build the `KieModule` from a Maven repository. In this case, the rules located by `DroolsRepositoryRulesetContainerImpl` are located by their Maven coordinates (groupId, artifactId, version). The artifact must contain a proper `kmodule.xml` file. +
See the <<cloud-altemistafwk-core-rules-drools-conf-configuration-repository>> section for further information.

[[cloud-altemistafwk-core-rules-drools-conf-configuration-repository]]
=== Centralised Knowledge Repository

The main purpose of using a centralised knowledge repository is to allow changes of the rules over time. This is accomplished by using any of the special values `LATEST`, `SNAPSHOT`, or `RELEASE` as versions, as well as version ranges:

[source,xml]
----
include::{basedir}/cloud-altemistafwk-core-rules-drools-conf/src/test/resources/spring/test-app-context-rules-repository.xml[tags=default]
----
<1> groupId, artifactId, version of the artifact that contains the rules (mandatory properties).
<2> If the version used is not a fixed vesion, enable the scanner to support changes of the rules over time.
<3> If the scanner is enabled, configure the scanning interval in milliseconds.

Please read the http://docs.jboss.org/drools/release/6.5.0.Final/drools-docs/html/ch02.html#d0e1901[KieModules, KieContainer and KIE-CI] and http://docs.jboss.org/drools/release/6.5.0.Final/drools-docs/html/ch02.html#d0e1920[KieScanner] sections of the http://docs.jboss.org/drools/release/6.5.0.Final/drools-docs/html/index.html[Drools Documentation].

CAUTION: To use this feature, <<cloud-altemistafwk-core-rules-drools-conf-maven-kie-ci>>.
