
:fragment:

The {framework} Business Rules Management (BRM) feature embeds a https://en.wikipedia.org/wiki/Business_rule_management_system[Business Rule Management System (BRMS)], also known as _business rules engine_, into your application.

A business rules engine is a great tool for efficient decision making because it can make decisions based on thousands of facts quickly, reliably, and repeatedly. Business rules are grouped in _rule sets_ and can be executed through execution sessions. 

Despite rules and rule sets can be defined inside the application, it is more usual to have them stored externally (in the file system or in a remote URL, by example). This possibility makes business rules engines more suitable for applications with highly dynamic business logic.

Currently, the only implementation provider available is https://www.drools.org/[Drools].

IMPORTANT: This feature embeds the BRMS in the application to be used internal and programatically. It does no cover or replace tools for rules development, knowledge bases as http://guvnor.jboss.org/[Guvnor], or rule management applications such as Drools Workbench.

== Executing business rules

The entry point of the rules engine is `RulesService`, that should be injected and invoked as a Spring Bean:

[source,java]
----
include::{basedir}/cloud-altemistafwk-core-rules-drools-conf/src/test/java/cloud/altemista/fwk/test/rules/DefaultTest.java[tags=autowire]
----

Using the `RulesService` bean, rules can be executed as follows:

[source,java]
----
include::{basedir}/cloud-altemistafwk-core-rules-drools-conf/src/test/java/cloud/altemista/fwk/test/rules/DefaultTest.java[tags=example]
----

This will execute the default ruleset using the implicit stateless session.
<1> Alternatively: `rulesService.defaultRuleset().executeRules(...)`;

== Rule sets

Usually, rules are grouped in rule sets and there are multiple rule sets in the application. It is possible to chosse which rule set is going to be executed as follows:

[source,java]
----
Date input1 = // ...
Date output1 = this.rulesService
		.getRuleset("calendar") //<1>
		.executeRules(input1);
output1.isBankHoliday();
// ...

Quiz input2 = // ...
Quiz output2 = this.rulesService
		.getRuleset("evaluation") //<1>
		.executeRules(input2);
output2.isQualified();
// ...

DummyBean input = // ...
DummyBean output = this.rulesService
		.defaultRuleset() //<2>
		.executeRules(input); 
----
<1> Use the `getRuleset()` method to retrieve an specific rule set from the rules service.
<2> If there is a default ruleset, it can be retrieved by `defaultRuleset()`.

Rule sets are referred to using logical names. Please refer to the specific <<cloud-altemistafwk-core-rules-drools-conf-configuration,implementation provider configuration>> section to know how logical names are mapped to actual rule sets.

== Rule sessions

A rule session is a runtime connection between a client and a rule engine. A rule session defines the type of the session that client wishes to establish:

Stateless rule session::

The stateless rule session works on a per-client request basis. An implicit stateless rule session is always available  (by example, all the previous examples were using the implicit stateless session). +
In {framework}, the stateless rule session is represented by the interface `StatelessRuleSession`.

Stateful rule session::

A stateful rule session is a dedicated session in which objects are not lost as long as the session is maintained between the client and the rules engine. The stateful rule session must be explicitly released when the client no longer requires the rule session. +
{framework} support stateful rule sessions, which use a slightly different API from the stateless rule session: `StatefulRuleSession`.

Execute rules using a stateful rule session as follows:

[source,java]
----
include::{basedir}/cloud-altemistafwk-core-rules-drools-conf/src/test/java/cloud/altemista/fwk/test/rules/StatefulTest.java[tags=example]
----
<1> Create a new stateful rule session for either a named rule set or the default one using the `createStatefulSession()` method.
<2> When executed in a stateful rule session, the rules can declare global variables. Set their values with the `addGlobal()` method.
<3> To add beans to the stateful rule session, use the `addObject` method. The rules will be executed over this beans. This method returns an unique identifier to monitor and update the bean values.
<4> `executeRules()` actually executes all the rules in the stateful rule session. Rules will be executed only over beans that have been added (`addObject()`) or updated (`updateObject()`).
<5> To re-execute the rule set over some beans, update them via `updateObject()`. Otherwise, the beans will be considered unmodified and rules will not process them.
<6> Always `release()` the stateful rule sessions when no longer required.

== Rules definition

The mechanism and languages for definition of business rules is dependent from the implementation provider.

When using Drools, the business rules are defined in _Drools Rule Language_ (DRL) files. An example:

[source]
.rules/greeting-rules.drl
----
package example; //<1>

import com.mycompany.application.module.model.Person; //<2>

rule "mister" //<3>
	when
		$i : Person( !female ); //<4>
	then
		$i.setGreeting("Hello, Mr. " + $i.getName() + "!"); //<5>
end

rule "miss" //<3>
	when
		$i : Person( female && (age < 18) ); //<4>
	then
		$i.setGreeting("Hi, Miss " + $i.getName() + "!"); //<5>
end

rule "mistress" //<3>
	when
		$i : Person( female && (age >= 18) ); //<4>
	then
		$i.setGreeting("Hello, Ms. " + $i.getName() + "!"); //<5>
end
----
<1> This package declaration only serves as a namespace for the rule names; the packages property of the `<kbase>` element in `kmodule.xml` files points to the location of the DRLs.
<2> Import statements work like import statements in Java.
<3> Rule names. A rule must have a name, unique within its rule package.
<4> The `when` clause defines the conditional part of the rule, also known as _Left Hand Side (LHS)_.
<5> The `then` clause defines the consequence or action part of the rule, also known as _Right Hand Side (RHS)_; this part should contain a list of actions to be executed.

TIP: Please refer to the http://docs.jboss.org/drools/release/6.5.0.Final/drools-docs/html/ch08.html[Rule Language Reference] of the http://docs.jboss.org/drools/release/6.5.0.Final/drools-docs/html/index.html[Drools Documentation] for a complete reference on the Drools Rule Language (DRL).
