
:fragment:

The _SOAP web service interface_ allows a project to define the web service interface using JAX-WS (Java API for XML Web Service) standard annotations: `@WebService`, `@WebMethod`, etc.

You can start with either the Java code of the web service interface (_contract last_ development style)
or with the WSDL contract and generate the necessary Java code from it (_contract first_ development style),
depending on what was shared by the web service owner.

If you are going for a _contract first_ development style, this feature can automatically generate the necessary Java code from the WSDL contract files.

The usage of the _SOAP web service interface_ feature consist in defining the web service interfaces for the web services that are going to be published or consumed.

For the web services publisher it is always recommended to use a _contract first_ development style: start with the WSDL contract and generate the necessary Java code from it.

In the consumer side, the most common scenario will be to gather the WSDL file from the actual service and follow a _contract first_ development style.

In any case, if the web service interface feature has been installed in a separate business interface project, the project can be shared between the publisher and the consumer (e.g.: if both sides are part of the same application).

== _Contract last_ development style

Simply use the standard JAX-WS annotations in the service definition:

[source,java]
.org/altemista/cloudfwk/test/soap/ExampleService.java
----
package org.altemista.cloudfwk.test.soap;

import javax.jws.WebMethod;
import javax.jws.WebService;

@WebService
public interface ExampleService {

  @WebMethod
  void exampleMethod();
}
----

== _Contract first_ development style

Given that the `cxf-codegen-plugin` is properly configured in the project, any WSDL file placed in the `wsdl` package of the resources folder.

[source,xml]
.wsdl/exampleService.wsdl
----
<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions name="ExampleServiceImplService"
    targetNamespace="http://soap.it.cloud.altemista.org/"
    xmlns:tns="http://soap.it.cloud.altemista.org/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:ns1="http://schemas.xmlsoap.org/soap/http">

  <wsdl:types>
    <xs:schema ... />
  </wsdl:types>

  <wsdl:message name="doNothing">
    <wsdl:part element="tns:doNothing" name="parameters"></wsdl:part>
  </wsdl:message>
  <wsdl:message ... />

  <wsdl:portType name="ExampleService">
    <wsdl:operation name="doNothing">
      <wsdl:input message="tns:doNothing" name="doNothing" />
      <wsdl:output message="tns:doNothingResponse" name="doNothingResponse" />
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding name="ExampleServiceImplServiceSoapBinding" type="tns:ExampleService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="doNothing">
      <soap:operation soapAction="" style="document"/>
      <wsdl:input name="doNothing">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="doNothingResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>

  <wsdl:service name="ExampleServiceImplService">
    <wsdl:port name="ExampleServiceImplPort"
        binding="tns:ExampleServiceImplServiceSoapBinding">
      <soap:address
          location="http://localhost:8080/altemista-cloudfwk-soap-it/soap/ExampleService"/>
    </wsdl:port>
  </wsdl:service>

</wsdl:definitions>
----
