
:fragment:

On the next example you can see how to configure a File Inbound Channel Adapter with an Integration Poller to check the status of a directory every 5 seconds and process the files. When the file will be processed, it will be copied in a output directory with a File Outbound Channel Adapter.

[source,xml,options="nowrap"]
./my-application-module-core/src/main/resources/spring/my-application-module-core-integration-file.xml
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns:integration="http://www.springframework.org/schema/integration"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.springframework.org/schema/beans"
	xmlns:file="http://www.springframework.org/schema/integration/file"
	xmlns:stream="http://www.springframework.org/schema/integration/stream"
	xsi:schemaLocation="http://www.springframework.org/schema/beans
			http://www.springframework.org/schema/beans/spring-beans.xsd
			http://www.springframework.org/schema/integration
			http://www.springframework.org/schema/integration/spring-integration.xsd
			http://www.springframework.org/schema/integration/file
			http://www.springframework.org/schema/integration/file/spring-integration-file.xsd
			http://www.springframework.org/schema/integration/stream
			http://www.springframework.org/schema/integration/stream/spring-integration-stream.xsd">
			
	<file:inbound-channel-adapter id="filesIn"
		directory="file:${test.integration.file.inbound.path}"
		prevent-duplicates="false">
		<integration:poller id="poller" fixed-delay="5000" />
	</file:inbound-channel-adapter> <!--1-->

	<integration:service-activator
		input-channel="filesIn" output-channel="filesOut" method="handleFile"
		ref="integrationFileHandler" /> <!--2-->

	<file:outbound-channel-adapter id="filesOut"
		directory="file:${test.integration.file.outbound.path}"
		delete-source-files="true" /> <!--3-->

	<bean id="integrationFileHandler"
		class="cloud.altemista.fwk.test.integration.file.IntegrationFileHandler" /> <!--4-->

</beans>
----
<1> *Integration File Inbound Channel Adapter* with a _Integration Poller_ to check if content in path directory change. The _Integration Poller_ is configure to execute a check every 5 seconds. 
<2> *Integration Service Activator* is the service activator to redirect and process with a handler the files from an Inbound Channel Adapter to an Outbound Channel Adapter.
<3> *Integration File Outbound Channel Adapter* for output files.
<4> *Integration File Handler* to process the input files. 

[source,properties,options="nowrap"]
----
test.integration.file.inbound.path=${java.io.tmpdir}/spring-integration-file/input/ <!--1-->
test.integration.file.outbound.path=${java.io.tmpdir}/spring-integration-file/output/ <!--2-->
----
<1> Input directory absolute path.
<2> Output directory absolute path.

//
[source,java,options="nowrap"]
.cloud.altemista.fwk.test.integration.file.IntegrationFileHandler
----
package cloud.altemista.fwk.test.integration.file;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class IntegrationFileHandler {
	
	Logger logger = LoggerFactory.getLogger(this.getClass());
	
	/**
	 * Handler Method witch read and write in a logger the input file content.
	 * @param input
	 * @return
	 * @throws FileNotFoundException
	 */
	
	public File handleFile(File input) throws FileNotFoundException {
		logger.info(" ====> Input file handled: " + input.getAbsolutePath());
		Scanner scanner = new Scanner(input);
		while (scanner.hasNextLine()) {
		   logger.info(" - "+scanner.nextLine());
		}
		scanner.close();
		logger.info(" ====> Copying file: " + input.getAbsolutePath());
		return input;
	}

}
----