
:fragment:

The {framework} mail server feature provides the ability of sending emails from the application with ease, using the _Simple Mail Transport Protocol_ (SMTP), and both synchronously or asynchronously.

== Sending an email

`MailService` is the main interface for the mail server module:

[source]
----
include::{basedir}/altemista-cloudfwk-core-mail-javamail-conf/src/test/java/org/altemista/cloudfwk/mail/javamail/MailServiceTest.java[tags=mailService]
----

This interface expects `Mail` instances. This instances can be created as follows:

[source]
----
Mail mail = new Mail(); // <1>
mail.setFrom("sender@nttdata.com"); // <2>
mail.setTo("receiver@nttdata.com");
mail.setSubject("Example subject");
mail.setText("Example text");
----
<1> The qualified name of the class is `org.altemista.cloudfwk.core.mail.model.Mail`
<2> The _from_, _to_, _carbon copy_ (_cc_), _blind carbon copy_ (_bcc_), _subject_, and _text_ fields are supported.

Once the email is built, use the `MailService.send()` method to send it synchronously:

[source]
----
this.mailService.send(mail);
----

Or, alternatively, use the `MailService.sendAsync()` method to send it asynchronously:

[source]
----
Future<MailStatus> mailStatus = this.mailService.sendAsync(mail);
----

TIP: The <<altemista-cloudfwk-core-async-conf,asynchronous executions module>> can be used to register the results to be retrieved later (e.g.: to implement a mailing porcess with a status page).

== HTML text content

The {framework} mail server feature supports HTML text content:

[source]
----
mail.setHtml(true);
mail.setText("<h1>Example text</h1>");
----

== Mail attachments

The {framework} mail server feature supports attachments to mails, both in-line and as a proper attachment.

{framework} mail attachments must implement the `org.altemista.cloudfwk.core.mail.model.Attachment` interface. The framework already provides the `ContentReadableAttachment` class; an adaptor for any `ContentReadable` to be an `Attachment`:

[source]
----
ContentReadable content = // ...

Attachment attachment = new ContentReadableAttachment(content); // <1>
attachment.setInline(true); // <2>

mail.setAttachment(attachment); // <3>
----
<1> Use the `ContentReadableAttachment` class to adapt any `ContentReadable` as an `Attachment`. Note that certain mail server implementations may have specific requirements over the attachments (e.g.: JavaMail API requires the `inputStream` to be a fresh one on each call).
<2> Set the _inline_ flag to make the attachment an in-line attachment (e.g.: embedded images).
<3> Use the `setAttachment()` method to set the attachments of the email prior to sending it.
