
:fragment:

To bootstrap and launch the Microservice-based {framework} application, implements the `org.altemista.cloudfwk.config.microservice.AltemistaCloudfwkMicroserviceBuilder` and call the _configureApplication_ method as follows:

[source]
.com.mycompany.application.microservice.MicroserviceApplication.java
----
@AltemistaCloudfkwMicroservice
public class MicroserviceApplication extends AltemistaCloudfwkMicroserviceBuilder {
    public static void main(String[] args) {
        configureApplication(new AltemistaCloudfwkApplicationBuilder(), MicroserviceApplication.class).run(args);
    }
}
----

This configureApplication method creates and runs a Microservice-based {framework} application (`org.altemista.cloudfwk.config.boot.AltemistaCloudfwkApplication`) like a Spring Boot-based application using the following configuration:

* Add the {framework} initializers to the application before the {framework} Spring context gets loaded.

* Uses the default Spring Boot configuration wherever possible.

 ** Imports the <<natures-core-internals,_core_ configuration of the framework>> first. All the features that are not dependent on the deployment platform will be loaded at this point.

* Includes all the Microservice-based application features found in the classpath, by importing their configuration classes (that will be under the package `org.altemista.cloudfwk.config.microservice`).

* Imports the application configuration files, located at `spring/*.xml` in the classpath.

The {framework} `@AltemistaCloudfwkMicroservice` annotate the main class with the `@EnableEurekaClient` and with a `@ComponentScan` over the same package as that annotation class.

[source,java]
----
include::{basedir}/altemista-cloudfwk-microservice-conf/src/main/java/org/altemista/cloudfwk/config/microservice/AltemistaCloudfwkMicroservice.java[tags=annotation]
----
<1> `@ComponentScan` over the same package as the `@AltemistaCloudfwkMicroservice` class.
<2> `@EnableEurekaClient` annotation to enable the application as Eureka Client

IMPORTANT: If the application has to be instantiate in a Eureka Server, the `spring.cloud.discovery.enabled` property will be set true.