package com.mycompany.application.module.repository;

/*
 * #%L
 * altemista-cloud persistence: MyBatis CONF
 * %%
 * Copyright (C) 2017 - 2018 NTT DATA Corporation
 * %%
 * All rights reserved.
 * Todos los derechos reservados.
 * #L%
 */


import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import com.mycompany.application.module.model.DemoTable;
import com.mycompany.application.module.model.DemoTableExample;
import com.mycompany.application.module.model.DemoTableWithBLOBs;

public interface DemoTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Tue May 10 11:55:42 CEST 2016
     */
    int countByExample(DemoTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Tue May 10 11:55:42 CEST 2016
     */
    int deleteByExample(DemoTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Tue May 10 11:55:42 CEST 2016
     */
    int deleteByPrimaryKey(Integer key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Tue May 10 11:55:42 CEST 2016
     */
    int insert(DemoTableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Tue May 10 11:55:42 CEST 2016
     */
    int insertSelective(DemoTableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Tue May 10 11:55:42 CEST 2016
     */
    List<DemoTableWithBLOBs> selectByExampleWithBLOBsWithRowbounds(DemoTableExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Tue May 10 11:55:42 CEST 2016
     */
    List<DemoTableWithBLOBs> selectByExampleWithBLOBs(DemoTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Tue May 10 11:55:42 CEST 2016
     */
    List<DemoTable> selectByExampleWithRowbounds(DemoTableExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Tue May 10 11:55:42 CEST 2016
     */
    List<DemoTable> selectByExample(DemoTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Tue May 10 11:55:42 CEST 2016
     */
    DemoTableWithBLOBs selectByPrimaryKey(Integer key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Tue May 10 11:55:42 CEST 2016
     */
    int updateByExampleSelective(@Param("record") DemoTableWithBLOBs record, @Param("example") DemoTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Tue May 10 11:55:42 CEST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") DemoTableWithBLOBs record, @Param("example") DemoTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Tue May 10 11:55:42 CEST 2016
     */
    int updateByExample(@Param("record") DemoTable record, @Param("example") DemoTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Tue May 10 11:55:42 CEST 2016
     */
    int updateByPrimaryKeySelective(DemoTableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Tue May 10 11:55:42 CEST 2016
     */
    int updateByPrimaryKeyWithBLOBs(DemoTableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Tue May 10 11:55:42 CEST 2016
     */
    int updateByPrimaryKey(DemoTable record);
	
	DemoTable findUsingCustomQuery();
	
	DemoTable findUsingUndefinedQuery();
}
