
:fragment:

In order to gain flexibility, such as supporting other technologies for the presentation layer, or provding a cleaner code base for pure API-based applications (i.e. without presentation layer), <<presentation-layer,presentation layer>> technologies have been decouples from the _web application_ nature.

Also, the mapping of the Spring MVC dispatcher servlet has changed to be aligned with Spring Boot-based applications. This decision has been taken to simplify particular settings previously required to keep {framework} compatible with both types of applications. Also, this change improves compatibility with 3rd party libraries that expect the dispatcher servlet to be mapped at `/{asterisk}` or `/`, such as Spring OAuth2.

== Spring MVC dispatcher servlet mapping

The mapping of the Spring MVC dispatcher servlet has changed from `/app/{asterisk}` to a more convenient `/{asterisk}` (actually, `/`). Besides properly updating the internal links of the application, applications should verify the following points:

* The `welcome-file-list` element of the deployment descriptor to set up a welcome page is now discouraged. To customize the welcome page, please read the <<cloud-altemistafwk-webapp-common-conf-welcomepage,welcome page>> section.

* It is now discouraged to rely on the default Servlet of the Servlet container:

	** Static resources should no longer be located at the `src/main/webapp` folder. Instead, serve static resources from `/WEB-INF/resources` and `/META-INF/resources` in the classpath. Please refer to the <<cloud-altemistafwk-webapp-conf-serving-web-content,serving web content>> section.
	
	** Dynamic views, such as JavaServer Pages (JSP), should not be accessed directly, but through a Spring MVC controller.

== Presentation layer features equivalence

Existing {framework} web applications not using <<presentation-layer-tiles>> or <<presentation-layer-jsf>> features must install the <<presentation-layer-jsp>> feature.

Applications using presentation layer technologies not natively supported by the framework should install the <<presentation-layer-common>> feature in order not to lose any of the functionality previously present in the _web application_ nature (internationalization, interceptors, etc.)
