
:fragment:

The {framework} Business Process Management (BPM) feature embeds a https://en.wikipedia.org/wiki/Business_process_management[Business Process Management (BPM)], or more precisely a https://en.wikipedia.org/wiki/Workflow_engine[_workflow engine_], into a {framework} application.

The framework provides a set of generic interfaces and the next concepts:

* process definitions, that define the steps and the workflow of the different processes.

* process instances, or executions of the existing process definitions.

* interactive tasks, steps where the process exceution waits for an input from the user or another system.

The provided implementation embeds http://activiti.org/[Activiti BPM Platform] in the application. The process definitions can be written in the standard http://www.bpmn.org/[Business Process Model And Notation (BPMN)] version 2.0 and any datasource can be used to persist the process instances, tasks and variables.

== Business processes and tasks

To use the workflow module, applications should use the generic interfaces defined in the module. This interfaces are provider independent; specific providers can inherit from them to offer additional, more specific methods.

There are three main interfaces:

* `WorkflowExecutionService` is the main interface of the workflow module and allows you to execute business processes via the `start()` methods.

* `WorkflowHumanTaskService` allows access to the "human" tasks. Usually, the application will mediate between the final user and the tasks, but sometimes the application can take care of some tasks internally.

* `WorkflowHistoryService` contains information about ongoing and past process instances.

This interfaces can be injected and invoked as Spring beans:

[source]
----
@Autowired
private WorkflowExecutionService executionService;

@Autowired
private WorkflowHumanTaskService humanTaskService;

@Autowired
private WorkflowHistoryService historyService;
----

The generic interfaces handle the following concetps:

* Process definition: the static workflow definition.

* Process instance: each instance, ongoing or past, of any process definition.

* Process instance variables: hold the state of a process instance.

* Task: where the process definition includes interactive tasks as any of its steps, a process instance will generate tasks. This tasks can be retrieved, resolved, skipped, delegated, etc. by the users (or by the system).

* Task candidate users or task candidate groups: users or groups that are expected to resolve the task.

* Task assignee: a task can be assigned to a single user, that will be the assignee of the task, and, thus, the responsible for resolving the task. An user (usually, a caniadate one) can claim a task to become the assignee for that task.

* Task owner: typically, the assignee will be the owner of the task. If the task is delegated to another user, then the delegated user will become the assignee for the task but the original user will still be the owner.

* Start and stop working on a task: indicates that some user have started to (or stopped) working on a task (e.g.: to prevent other users to work on the same task).

* Suspend and resume working on a task: indicates a temporary pause of the work on a task.

* Claiming and releasing tasks: the process of claiming a task is to become both the owner and the assignee for the task. Releasing a task is to return the task to the pool of unclaimed tasks. An already claimed task can not be claimed again without being released first.

* Delegating and resolving tasks: to delegate a task is just setting a new assignee for the task and it is typically done by the owner of the task. The assignee can resolve a task, changing its state (the process instance variables) and returning the task to the owner.

* Completing a task: updates the process instance state and completes the task so its process instace will continue advancing through the defined workflow.

For detailed information, check the Javadoc of the interfaces.

== Authentication awareness

Both `WorkflowExecutionService` and `WorkflowHumanTaskService` contain methods that can be executed with authentication awareness: can be executed without user details, using the current authenticated user, or providing any user ID.
The effect on the method execution varies from one method (or implementation provider) to another.
By example, the `WorkflowHumanTaskService.claimTask()` method is most likely not suitable to be executed anonymously but rather using the current user.
As a general rule, authentication information will be silently ignored for the methods where the implementation provider does not support it. 

There are three methods in the `AuthenticableWorkflowService` interface (that those services extend):

* `anonymously()` will use no authentication information when invoking the authentication aware methods.

* `withCurrentUser()` will use the current user when invoking the authentication aware methods. Obviously, a security context is required to use this method.

* `withUser(userId)` will use the specific user when invoking the authentication aware methods.

Please note that the workflow services are stateless, so the correct usage of one of these methods is as follows:

[source]
----
@Autowired
private WorkflowExecutionService executionService;
// ...

this.executionService.withUser("john_doe").start("example");//<1>
// ...

this.executionService.withCurrentUser();
this.executionService.start("example");//<2>
----
<1> This will start a new process instance using the user `"john_doe"`.
<2> Despite `withCurrentUser()` being called in the previous line, this will start a new process instance anonymously. `WorkflowExecutionService` is stateless.

For your convenience, both `WorkflowExecutionService` and `WorkflowHumanTaskService` interfaces contain their authentication aware methods bridges to the anonymous execution: 

[source]
----
@Autowired
private WorkflowExecutionService executionService;
// ...

this.executionService.start("example");//<1>
this.executionService.anonymously().start("example");//<1>
----
<1> Both sentences are equivalent.

== Process definitions

The process definitions are stored in the workflow internal database and are managed by the workflow engine itself. There is no support in the module to manage the deployment, undeployment, and versioning of this process definitions. This is purely intentional, as usually the management of the life-cycle of the process definitions is not part of the application (this is in fact quite similar to the database repository interfaces, that usually query the database but do not alter the database schema).

However, the Activiti implementation module includes an automatic deployment of process definitions so when the application is initially deployed, or a new version of an existing application is deployed, the process definitions the application uses is upgraded as well. This is intended to be used when Activiti is embedded inside the application, but can be undesirable if the application points to an existing Activiti installation, managed independently, outside the application.

To declare the process definitions that are to be deployed or redeployed with the application, simpy put them in stadard http://www.bpmn.org/[BPMN 2.0] format in the `workflow` package inside the classpath, with the `.bpmn20.xml` extension.

Here is an example:

[source,xml]
.workflow/example.bpmn20.xml
----
include::{basedir}/altemista-cloudfwk-core-workflow-activiti-conf/src/test/resources/workflow/oneTaskProcess.bpmn20.xml[]
----
<1> In this example, `oneTaskProcess` is the identifier of the process definition and, hence, the `processDefinitionId` to be used when invoking `WorkflowExecutionService.start()` methods.
<2> This example workflow uses Activiti extensions in the BPMN 2.0 definition. In this example, the authenticated user that starts the process instance will be stored in the process variable named "initiator".
<3> This workflow includes a human task. Each process instance will create a new, unclaimed, task and will wait until that task is completed.

It is outside the scope of this document to explain BPMN 2.0 in detail, so please refer to the proper documentation such as the http://www.omg.org/spec/BPMN/2.0/[BPMN 2.0 normative], the http://www.omg.org/cgi-bin/doc?dtc/10-06-02[BPMN 2.0 examples non-normative document], or even the http://activiti.org/userguide/index.html#bpmn20[BPMN 2.0 introduction chapter] of the Activiti users guide.
