
:fragment:

{framework} Integration Features enables favors the integration between different communication systems using https://spring.io/projects/spring-integration[Spring Integration^]

Extends the Spring programming model to support the well-known Enterprise Integration Patterns. Spring Integration enables lightweight messaging within Spring-based applications and supports integration with external systems via declarative adapters. Those adapters provide a higher-level of abstraction over Spring’s support for remoting, messaging, and scheduling. Spring Integration’s primary goal is to provide a simple model for building enterprise integration solutions while maintaining the separation of concerns that is essential for producing maintainable, testable code.

Using the Spring Framework encourages developers to code using interfaces and use dependency injection (DI) to provide a Plain Old Java Object (POJO) with the dependencies it needs to perform its tasks. Spring Integration takes this concept one step further, where POJOs are wired together using a messaging paradigm and individual components may not be aware of other components in the application. Such an application is built by assembling fine-grained reusable components to form a higher level of functionality. WIth careful design, these flows can be modularized and also reused at an even higher level.

In addition to wiring together fine-grained components, Spring Integration provides a wide selection of channel adapters and gateways to communicate with external systems. Channel Adapters are used for one-way integration (send or receive); gateways are used for request/reply scenarios (inbound or outbound). For a full list of adapters and gateways, refer to the reference documentation.

The Spring Cloud Stream project builds on Spring Integration, where Spring Integration is used as an engine for message-driven microservices.

= Goals and Principles

Spring Integration is motivated by the following goals:

* Provide a simple model for implementing complex enterprise integration solutions.
* Facilitate asynchronous, message-driven behavior within a Spring-based application.
* Promote intuitive, incremental adoption for existing Spring users.
* Spring Integration is guided by the following principles:

Components should be loosely coupled for modularity and testability.

* The framework should enforce separation of concerns between business logic and integration logic.
* Extension points should be abstract in nature but within well-defined boundaries to promote reuse and portability.

== Main Components

=== Message
In Spring Integration, a Message is a generic wrapper for any Java object combined with metadata used by the framework while handling that object. It consists of a payload and headers. The payload can be of any type and the headers hold commonly required information such as id, timestamp, correlation id, and return address. Headers are also used for passing values to and from connected transports.

=== Message Channel
A Message Channel may follow either Point-to-Point or Publish/Subscribe semantics. With a Point-to-Point channel, at most one consumer can receive each Message sent to the channel. Publish/Subscribe channels, on the other hand, will attempt to broadcast each Message to all of its subscribers. Spring Integration supports both of these.

=== Message Endpoints
A Message Endpoint represents the "filter" of a pipes-and-filters architecture. As mentioned above, the endpoint’s primary role is to connect application code to the messaging framework and to do so in a non-invasive manner. In other words, the application code should ideally have no awareness of the Message objects or the Message Channels.

==== *Transformer*
A Message Transformer is responsible for converting a Message’s content or structure and returning the modified Message.

==== *Filter*
A Message Filter determines whether a Message should be passed to an output channel at all.

==== *Router*
A Message Router is responsible for deciding what channel or channels should receive the Message next (if any).

==== *Splitter*
A Splitter is another type of Message Endpoint whose responsibility is to accept a Message from its input channel, split that Message into multiple Messages, and then send each of those to its output channel.

==== *Aggregator*
Basically a mirror-image of the Splitter, the Aggregator is a type of Message Endpoint that receives multiple Messages and combines them into a single Message.

==== *Service Activator*
A Service Activator is a generic endpoint for connecting a service instance to the messaging system. The input Message Channel must be configured, and if the service method to be invoked is capable of returning a value, an output Message Channel may also be provided.

==== *Channel Adapter*
A Channel Adapter is an endpoint that connects a Message Channel to some other system or transport. Channel Adapters may be either inbound or outbound.

= {framework} adapters

In the following table we show you the list of {framework} adapters

.Spring Integration Adapters added in {framework}
[cols="25,75",options="header"]
|===
^.^|Name
   |Description 
^.^|<<integration-amqp-feature,Integration AMQP Feature>>
   |Spring Integration provides Channel Adapters for receiving and sending messages using the Advanced Message Queuing Protocol (AMQP).
^.^|<<integration-file-feature,Integration File Feature>>
   |Spring Integration File support extends the Spring Integration Core with a dedicated vocabulary to deal with reading, writing, and transforming files.
^.^|<<integration-ftp-feature,Integration FTP Feature>>
   |Integration FTP Adapter support for file transfer operations via FTP and FTPS.
^.^|<<integration-http-feature,Integration HTTP Feature>>
   |The HTTP support allows for the execution of HTTP requests and the processing of inbound HTTP requests.
^.^|<<integration-jms-feature,Integration JMS Feature>>
   |Spring Integration Provides Channel Adapters for receiving and sending JMS messages.
^.^|<<integration-jmx-feature,Integration JMX Feature>>
   |Spring Integration provides Channel Adapters for receiving and publishing JMX Notifications.
^.^|<<integration-jpa-feature,Integration JPA Feature>>
   |Spring Integration provides support for retrieving and persisting JPA entity objects.
^.^|<<integration-mail-feature,Integration Mail Feature>>
   |Spring Integration provides support for outbound email with the MailSendingMessageHandler. It delegates to a configured instance of Spring's JavaMailSender 
^.^|<<integration-mqtt-feature,Integration MQTT Feature>>
   |Spring Integration provides inbound and outbound channel adapters supporting the MQ Telemetry Transport (MQTT) protocol.
^.^|<<integration-resource-feature,Integration Resource Feature>>
   |The Resource Inbound Channel Adapter is a polling adapter that creates a Message whose payload is a collection of Resource objects.
^.^|<<integration-rmi-feature,Integration RMI Feature>>
   |Spring Integration provides inbound and outbound channel adapters supporting the RMI protocol. 
^.^|<<integration-sftp-feature,Integration SFTP Feature>>
   |Integration SFTP Adapter support for file transfer operations via SFTP.
^.^|<<integration-ip-feature,Integration TCP and UDP Feature>>
   |Spring Integration provides Channel Adapters for receiving and sending messages over internet protocols (TCP and UDP).
^.^|<<integration-ws-feature,Integration Web Services Feature>>
   |Spring Integration provides Channel Adapters for receiving and sending messages over WebServices.
^.^|<<integration-websocket-feature,Integration Web Sockets Feature>>
   |Spring Integration provides Channel Adapters for receiving and sending messages over Web Sockets.
|===