package cloud.altemista.fwk.it.model;

/*
 * #%L
 * altemista-cloud performance module integration tests
 * %%
 * Copyright (C) 2017 NTT DATA Corporation
 * %%
 * All rights reserved.
 * Todos los derechos reservados.
 * #L%
 */


import java.io.Serializable;

public class DemoTableWithBLOBs extends DemoTable implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEMO_TABLE.BINARY_FIELD
     *
     * @mbggenerated Sat Jun 11 14:07:11 CEST 2016
     */
    private byte[] binaryField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEMO_TABLE.VARBINARY_FIELD
     *
     * @mbggenerated Sat Jun 11 14:07:11 CEST 2016
     */
    private byte[] varbinaryField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DEMO_TABLE.BLOB_FIELD
     *
     * @mbggenerated Sat Jun 11 14:07:11 CEST 2016
     */
    private byte[] blobField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Sat Jun 11 14:07:11 CEST 2016
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEMO_TABLE.BINARY_FIELD
     *
     * @return the value of DEMO_TABLE.BINARY_FIELD
     *
     * @mbggenerated Sat Jun 11 14:07:11 CEST 2016
     */
    public byte[] getBinaryField() {
        return binaryField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEMO_TABLE.BINARY_FIELD
     *
     * @param binaryField the value for DEMO_TABLE.BINARY_FIELD
     *
     * @mbggenerated Sat Jun 11 14:07:11 CEST 2016
     */
    public void setBinaryField(byte[] binaryField) {
        this.binaryField = binaryField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEMO_TABLE.VARBINARY_FIELD
     *
     * @return the value of DEMO_TABLE.VARBINARY_FIELD
     *
     * @mbggenerated Sat Jun 11 14:07:11 CEST 2016
     */
    public byte[] getVarbinaryField() {
        return varbinaryField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEMO_TABLE.VARBINARY_FIELD
     *
     * @param varbinaryField the value for DEMO_TABLE.VARBINARY_FIELD
     *
     * @mbggenerated Sat Jun 11 14:07:11 CEST 2016
     */
    public void setVarbinaryField(byte[] varbinaryField) {
        this.varbinaryField = varbinaryField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DEMO_TABLE.BLOB_FIELD
     *
     * @return the value of DEMO_TABLE.BLOB_FIELD
     *
     * @mbggenerated Sat Jun 11 14:07:11 CEST 2016
     */
    public byte[] getBlobField() {
        return blobField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DEMO_TABLE.BLOB_FIELD
     *
     * @param blobField the value for DEMO_TABLE.BLOB_FIELD
     *
     * @mbggenerated Sat Jun 11 14:07:11 CEST 2016
     */
    public void setBlobField(byte[] blobField) {
        this.blobField = blobField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Sat Jun 11 14:07:11 CEST 2016
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DemoTableWithBLOBs other = (DemoTableWithBLOBs) that;
        return (this.getKey() == null ? other.getKey() == null : this.getKey().equals(other.getKey()))
            && (this.getIntegerField() == null ? other.getIntegerField() == null : this.getIntegerField().equals(other.getIntegerField()))
            && (this.getIntField() == null ? other.getIntField() == null : this.getIntField().equals(other.getIntField()))
            && (this.getSmallintField() == null ? other.getSmallintField() == null : this.getSmallintField().equals(other.getSmallintField()))
            && (this.getTinyintField() == null ? other.getTinyintField() == null : this.getTinyintField().equals(other.getTinyintField()))
            && (this.getBigintField() == null ? other.getBigintField() == null : this.getBigintField().equals(other.getBigintField()))
            && (this.getDecimalField() == null ? other.getDecimalField() == null : this.getDecimalField().equals(other.getDecimalField()))
            && (this.getNumericField() == null ? other.getNumericField() == null : this.getNumericField().equals(other.getNumericField()))
            && (this.getFloatField() == null ? other.getFloatField() == null : this.getFloatField().equals(other.getFloatField()))
            && (this.getDoubleField() == null ? other.getDoubleField() == null : this.getDoubleField().equals(other.getDoubleField()))
            && (this.getDateField() == null ? other.getDateField() == null : this.getDateField().equals(other.getDateField()))
            && (this.getDatetimeField() == null ? other.getDatetimeField() == null : this.getDatetimeField().equals(other.getDatetimeField()))
            && (this.getTimestampField() == null ? other.getTimestampField() == null : this.getTimestampField().equals(other.getTimestampField()))
            && (this.getTimeField() == null ? other.getTimeField() == null : this.getTimeField().equals(other.getTimeField()))
            && (this.getCharField() == null ? other.getCharField() == null : this.getCharField().equals(other.getCharField()))
            && (this.getVarcharField() == null ? other.getVarcharField() == null : this.getVarcharField().equals(other.getVarcharField()))
            && (this.getBinaryField() == null ? other.getBinaryField() == null : this.getBinaryField().equals(other.getBinaryField()))
            && (this.getVarbinaryField() == null ? other.getVarbinaryField() == null : this.getVarbinaryField().equals(other.getVarbinaryField()))
            && (this.getBlobField() == null ? other.getBlobField() == null : this.getBlobField().equals(other.getBlobField()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Sat Jun 11 14:07:11 CEST 2016
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getKey() == null) ? 0 : getKey().hashCode());
        result = prime * result + ((getIntegerField() == null) ? 0 : getIntegerField().hashCode());
        result = prime * result + ((getIntField() == null) ? 0 : getIntField().hashCode());
        result = prime * result + ((getSmallintField() == null) ? 0 : getSmallintField().hashCode());
        result = prime * result + ((getTinyintField() == null) ? 0 : getTinyintField().hashCode());
        result = prime * result + ((getBigintField() == null) ? 0 : getBigintField().hashCode());
        result = prime * result + ((getDecimalField() == null) ? 0 : getDecimalField().hashCode());
        result = prime * result + ((getNumericField() == null) ? 0 : getNumericField().hashCode());
        result = prime * result + ((getFloatField() == null) ? 0 : getFloatField().hashCode());
        result = prime * result + ((getDoubleField() == null) ? 0 : getDoubleField().hashCode());
        result = prime * result + ((getDateField() == null) ? 0 : getDateField().hashCode());
        result = prime * result + ((getDatetimeField() == null) ? 0 : getDatetimeField().hashCode());
        result = prime * result + ((getTimestampField() == null) ? 0 : getTimestampField().hashCode());
        result = prime * result + ((getTimeField() == null) ? 0 : getTimeField().hashCode());
        result = prime * result + ((getCharField() == null) ? 0 : getCharField().hashCode());
        result = prime * result + ((getVarcharField() == null) ? 0 : getVarcharField().hashCode());
        result = prime * result + ((getBinaryField() == null) ? 0 : getBinaryField().hashCode());
        result = prime * result + ((getVarbinaryField() == null) ? 0 : getVarbinaryField().hashCode());
        result = prime * result + ((getBlobField() == null) ? 0 : getBlobField().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DEMO_TABLE
     *
     * @mbggenerated Sat Jun 11 14:07:11 CEST 2016
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", binaryField=").append(binaryField);
        sb.append(", varbinaryField=").append(varbinaryField);
        sb.append(", blobField=").append(blobField);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
