
:fragment:

You can configure all the infrastructure properties in:

[source,properties,options="nowrap"]
./my-application-env/src/main/resources/config/properties/my-application-storage-env.properties
----
#
# Azure Storage File Feature Properties
#

#Specifies the Azure Resource Group that contains your Azure Storage account.
spring.cloud.azure.resource-group=${azureresourcegroup}   <!--1-->

#Specifies the geographical region that you specified when you created your Azure Storage account.
spring.cloud.azure.region=West Europe  

#Specifies Azure Storage account that you created earlier in this tutorial.
spring.cloud.azure.storage.account=${azurestorageaccount}  <!--2-->

#Specifies Azure credential file that you created earlier in this tutorial.
spring.cloud.azure.credential-file-path=my.azureauth   <!--3-->
----
<1> Add ${azureresourcegroup} as environment variable.
<2> Add ${azurestorageaccount} as environment variable.
<3> To create the azure credential file follow this tutorial.

=== Create an Azure Credential File

IMPORTANT: To use the Azure Storage feature, the Azure Cli software needs to be installed in your environment.

Open a command prompt and 
navigate to the resources directory of your Spring Boot app. 
For example:
[source,Shell]
-----------------
cd C:\SpringBoot\new-application\src\main\resources
-----------------

Sign in to your Azure account whit Azure CLI:
[source,Shell]
-----------------
az login
-----------------

List your subscriptions:
[source,Shell]
-----------------
az account list
-----------------
Azure will return a list of your subscriptions, and you will need to copy the GUID for the subscription that you want to use. 
For example:
[source,xml]
-----------------
[
  {
    "cloudName": "AzureCloud",
    "id": "11111111-1111-1111-1111-111111111111",
    "isDefault": true,
    "name": "Converted Windows Azure MSDN - Visual Studio Ultimate",
    "state": "Enabled",
    "tenantId": "22222222-2222-2222-2222-222222222222",
    "user": {
      "name": "example@example.com",
      "type": "user"
    }
  }
]
-----------------

Specify the GUID for the subscription you want to use with Azure; for example:
[source,Shell]
-----------------
az account set -s 11111111-1111-1111-1111-111111111111
-----------------

Create your Azure Credential file:
[source,Shell]
-----------------
az ad sp create-for-rbac --sdk-auth > my.azureauth
-----------------
This command will create a my.azureauth file in your resources directory 