package cloud.altemista.fwk.remindersmybatis.module.repository;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import cloud.altemista.fwk.remindersmybatis.module.model.RmndrsRoles;
import cloud.altemista.fwk.remindersmybatis.module.model.RmndrsRolesExample;

public interface RmndrsRolesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_ROLES
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int countByExample(RmndrsRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_ROLES
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int deleteByExample(RmndrsRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_ROLES
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_ROLES
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int insert(RmndrsRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_ROLES
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int insertSelective(RmndrsRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_ROLES
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    List<RmndrsRoles> selectByExampleWithRowbounds(RmndrsRolesExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_ROLES
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    List<RmndrsRoles> selectByExample(RmndrsRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_ROLES
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    RmndrsRoles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_ROLES
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int updateByExampleSelective(@Param("record") RmndrsRoles record, @Param("example") RmndrsRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_ROLES
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int updateByExample(@Param("record") RmndrsRoles record, @Param("example") RmndrsRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_ROLES
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int updateByPrimaryKeySelective(RmndrsRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table RMNDRS_ROLES
     *
     * @mbggenerated Mon Jun 06 11:21:55 CEST 2016
     */
    int updateByPrimaryKey(RmndrsRoles record);
}