
:fragment:

The JasperReports-based implementation of the reporting feature sets up a `JasperReportBuilderImpl` instance as the bean that implements the `ReportBuilder` interface.

When using this implementation, the `ReportBean` instance returned by the builder will be of type `JasperReportBean`. A JasperReports `JRDataSource` can be set to the report bean as the source of data to populate the report.

With the default configuration, the application can populate the report as follows:

[source]
.JasperReportBuilderExample.java
----
include::{basedir}/altemista-cloudfwk-core-reporting-jasper-conf/src/test/java/org/altemista/cloudfwk/example/reporting/ReportBuilderExample.java[tags=jasper]
----
<1> Build the `ReportBean` as usual.
<2> Cast the report bean as a `JasperReportBean` and set the proper `JRDataSource` for feeding the report.
<3> Render the report as usual.

CAUTION: Though very simple, this approach will tighly couple your code with the JasperReports-based implementation of the reporting feature and with JasperReports itself. +
Always prefer other `JasperFiller` implementations that feed the report from the database, removing this coupling from your code. +
Please refer to the <<altemista-cloudfwk-core-reporting-jasper-conf-configuration,configuration>> section to known which `JasperFiller` implementation are available and how to change them.
