
:fragment:

In this section you will see how to configure and execute a web service request with the {framework} Integration WebServices feature. The request will be executed through a request gateway 

[source,xml,options="nowrap"]
./new-application-module-core/src/main/resources/spring/new-application-module-core-integration-ws.xml
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:integration="http://www.springframework.org/schema/integration"
	xmlns:ws="http://www.springframework.org/schema/integration/ws"
	xmlns:context="http://www.springframework.org/schema/context"
	xsi:schemaLocation="http://www.springframework.org/schema/beans
			http://www.springframework.org/schema/beans/spring-beans.xsd
			http://www.springframework.org/schema/integration
			http://www.springframework.org/schema/integration/spring-integration.xsd
			http://www.springframework.org/schema/integration/ws
			http://www.springframework.org/schema/integration/ws/spring-integration-ws.xsd
			http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context.xsd">

	<context:component-scan base-package="com.mycompany.application.module.ws.soap" />
	
	<integration:gateway
		service-interface="com.mycompany.application.module.ws.gateway.RequestGateway"
		id="wsRequestGateway" default-request-channel="wsRequestChannel" /> <!--1-->

	<integration:channel id="wsRequestChannel"/> <!--2-->
	
	<bean id="customMarshaller"
		class="com.mycompany.application.module.ws.marshaller.CustomMarshaller">
	</bean>  <!--3-->

	<ws:outbound-gateway marshaller="customMarshaller"
		uri="http://localhost:${server.port}/soap/CustomWebservice" request-channel="wsRequestChannel" reply-channel="outputChannel">
	</ws:outbound-gateway>  <!--4-->
	
	<bean id="customServiceActivator" class="com.mycompany.application.module.ws.service.CustomServiceActivator"/>  <!--5-->
	
	<integration:service-activator input-channel="outputChannel" ref="customServiceActivator" method="customMethodServiceActivator" />  <!--6-->
	
	<integration:channel id="outputChannel"/>  <!--7-->
</beans>
----
<1> *Integration Gateway* for messages sending.
<2> *Integration Channel*
<3> *Custom Marshaller Bean* for XML to JAVA marshalling and unmarshalling.
<4> *Integration Web Service Outbound Gateway* for message sending over Web Service endpoint.
<5> *Custom Service Activator Bean*
<6> *Custom Service Activator* to send message over Output Channel.
<7> *Integration Channel* for output requests.

The CustomMarshaller

[source,java,options="nowrap"]
.com.mycompany.application.module.ws.marshaller.CustomMarshaller
----
package com.mycompany.application.module.ws.marshaller;

import java.io.IOException;

import javax.xml.transform.Result;
import javax.xml.transform.Source;
import javax.xml.transform.TransformerFactory;
import javax.xml.transform.dom.DOMSource;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.oxm.Marshaller;
import org.springframework.oxm.Unmarshaller;
import org.springframework.oxm.XmlMappingException;
import org.springframework.xml.transform.StringSource;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

public class CustomMarshaller  implements Marshaller, Unmarshaller {

	Logger logger = LoggerFactory.getLogger(this.getClass());

	@Override
	public boolean supports(Class<?> clazz) {
		return false;
	}

	@Override
	public void marshal(Object graph, Result result) throws IOException, XmlMappingException {

		final String param = (String) graph;

		final String xmlString = 
				"<soap:testWebserviceMethod xmlns:soap=\"http://soap.ws.integration.it.cloud.altemista.org/\">"
						+ "<param>"+param+"</param>"
						+ "</soap:testWebserviceMethod>";

		try {
			TransformerFactory.newInstance().newTransformer().transform(new StringSource(xmlString), result);
		} catch (Exception e) {
			e.printStackTrace();
		}

	}

	@Override
	public String unmarshal(Source source) throws IOException, XmlMappingException {

		final NodeList nodeList = ((DOMSource)source).getNode().getChildNodes();

		String result = null;
		
		for (int i = 0; i < nodeList.getLength(); i++) {
			final Node returnNode = nodeList.item(i);
			if (returnNode!=null && returnNode.getNodeName().equals("return")){
				result = returnNode.getTextContent();
			}
		}
		
		logger.info("Unmarshall result: "+result);
		
		return result;
	}

}

----

The request Gateway class

[source,java,options="nowrap"]
.com.mycompany.application.module.ws.gateway.RequestGateway
----
package com.mycompany.application.module.ws.gateway;


public interface RequestGateway {

	public String requestGatewayTestMethod(String param);
	
}
----

The Custom Service Activator

[source,java,options="nowrap"]
.com.mycompany.application.module.ws.service.CustomServiceActivator
----
package com.mycompany.application.module.ws.service;

public class CustomServiceActivator {

	public String customMethodServiceActivator(String param){
		return param;
	}
}
----

If you like to make a request through the gateway you can develop something like this.

[source,java,options="nowrap"]
.com.mycompany.application.module.ws.controller.CustomRestController
----
package com.mycompany.application.module.ws.controller;

import java.util.HashMap;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RestController;
import com.mycompany.application.module.ws.gateway.RequestGateway;

@RestController
@RequestMapping(CustomRestController.MAPPING)
public class CustomRestController {

	public static final String MAPPING = "/integrationws";
	
	Logger logger = LoggerFactory.getLogger(this.getClass());
	
	@Autowired
	private RequestGateway requestGateway;

	@RequestMapping(value="test/{param}", method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE)
	public ResponseEntity<Map<String,String>> testMethod(@PathVariable("param") String param) {
		Map<String,String> result = new HashMap<String,String>();
		String responseValue = requestGateway.requestGatewayTestMethod("OK!!!"); //<1>
		result.put("result",responseValue);
		return ResponseEntity.ok(result);
	}
}

----
<1> You can send the message through the request gateway and get the response.