apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: dev-${CICD_ID}-pipeline
      name: dev-${CICD_ID}-pipeline
    name: dev-${CICD_ID}-pipeline
  spec:    
    runPolicy: Serial
    source:
      type: "Git"
      git:
        uri: http://gogs:3000/${GOGS_USER}/cicd.git
        ref: master
      sourceSecret:
          name: gitbasicauth
      contextDir: ${APP_AI}
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: dev.jenkinsfile
        env:
        - name: GIT_SSL_NO_VERIFY
          value: "true"
        - name: version
          value: stable      
      type: JenkinsPipeline
    triggers:
      - type: GitHub
        github:
          secret: ${WEBHOOK_SECRET}
      - type: Generic
        generic:
          secret: ${WEBHOOK_SECRET}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: int-${CICD_ID}-pipeline
      name: int-${CICD_ID}-pipeline
    name: int-${CICD_ID}-pipeline
  spec:    
    runPolicy: Serial
    source:
      type: "Git"
      git:
        uri: http://gogs:3000/${GOGS_USER}/cicd.git
        ref: master
      sourceSecret:
          name: gitbasicauth
      contextDir: ${APP_AI}
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: int.jenkinsfile
        env:
        - name: GIT_SSL_NO_VERIFY
          value: "true"
        - name: version
          value: stable      
      type: JenkinsPipeline
    triggers: []
        