
:fragment:

On the next example you can see how to configure a FTP Inbound Channel Adapter with an Integration Poller to check the status of a remote directory every 5 seconds and process the files. When the file will be processed, it will be copied in a remote output directory with a FTP Outbound Channel Adapter.

[source,xml,options="nowrap"]
./my-application-module-core/src/main/resources/spring/my-application-module-core-integration-ftp.xml
----
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:integration="http://www.springframework.org/schema/integration"
	xmlns:ftp="http://www.springframework.org/schema/integration/ftp"
	xmlns:context="http://www.springframework.org/schema/context"
	xsi:schemaLocation="http://www.springframework.org/schema/beans
			http://www.springframework.org/schema/beans/spring-beans.xsd
			http://www.springframework.org/schema/integration
			http://www.springframework.org/schema/integration/spring-integration-5.0.xsd
			http://www.springframework.org/schema/integration/ftp
			http://www.springframework.org/schema/integration/ftp/spring-integration-ftp-5.0.xsd
			http://www.springframework.org/schema/context 
			http://www.springframework.org/schema/context/spring-context.xsd">

	<bean id="ftpClientFactory"
		class="org.springframework.integration.ftp.session.DefaultFtpSessionFactory">
		<property name="host" value="${spring.integration.ftp.host}" />
		<property name="port" value="${spring.integration.ftp.port}" />
		<property name="username" value="${spring.integration.ftp.username}" />
		<property name="password" value="${spring.integration.ftp.password}" />
	</bean> <!--1-->

	<bean id="cachingSessionFactory"
		class="org.springframework.integration.file.remote.session.CachingSessionFactory">
		<constructor-arg ref="ftpClientFactory" />
	</bean>

	<integration:channel id="ftpInChannel">
		<integration:queue />
	</integration:channel> <!--2-->

	<ftp:inbound-channel-adapter id="ftpInbound"
		channel="ftpInChannel" session-factory="ftpClientFactory"
		auto-create-local-directory="true" delete-remote-files="false"
		remote-directory="/integration/" local-directory="/temp/ftpInbound"
		filename-pattern="*.txt" >
		<integration:poller fixed-rate="5000" />
	</ftp:inbound-channel-adapter>  <!--3-->

	<integration:channel id="ftpOutChannel" />  <!--4-->

	<ftp:outbound-channel-adapter
		session-factory="cachingSessionFactory" id="ftpOutbound" channel="ftpOutChannel"
		remote-directory="/integration/out" auto-create-directory="true">
		<ftp:request-handler-advice-chain>
			<integration:retry-advice />
		</ftp:request-handler-advice-chain>
	</ftp:outbound-channel-adapter>  <!--5-->

</beans>
----
<1> *FTP Client Session Factory* for FTP server connection configuration.
<2> *FTP Input Channel* with Integration Queue.
<3> *Integration FTP Inbound Channel Adapter* with a _Integration Poller_ to check if content in remote path directory change. The _Integration Poller_ is configure to execute a check every 5 seconds. 
<4> *FTP Output Channel*
<5> *Integration FTP Outbound Channel Adapter* for remote output files.