
:fragment:

http://projects.spring.io/spring-webflow/[Spring Web Flow] allows implementing the _flows_ of a web application. A flow encapsulates a sequence of steps that guide a user through the execution of some business task.

== Flow definitions

The default configuration of the Spring Web Flow feature will automatically look for flow definitions at the locations `+WEB-INF/flows/**/*-flow.xml+` and `+META-INF/flows/**/*-flow.xml+`. Those flows will be mapped directly inside the Spring dispatcher servlet base mapping with the `-flow` suffix. E.g.: a request `/example-flow` will be processed by the entry point of the flow defined by `WEB-INF/flows/example-flow.xml` file.

An example flow definition:
[source,xml]
.WEB-INF/flows/example-flow.xml
----
include::{basedir}/altemista-cloudfwk-webapp-webflow-conf/src/test/resources/META-INF/flows/example-flow.xml[]
----
<1> All states of the flow are defined within the `flow` element. The first state defined becomes the flow's starting point.
<2> Use `view-state` to define a step of the flow that returns a view, rendered by the currently configured view technology.
<3>	Use `transition` to handle events that occur within a state.
<4> Use `end-state` to define a terminal step of the flow, or a flow outcome.
<5> Use `var` to declare a flow variable.
<6> Use `evaluate` to invoke actions, usually implemented as presentation services (or even business services) of the application.
<7> Use `output` to declare flow outcomes.

For further information, please refer to the http://docs.spring.io/spring-webflow/docs/current/reference/html/defining-flows.html[defining flows] chapter of the http://docs.spring.io/spring-webflow/docs/current/reference/html/[Spring Web Flow Reference Guide].
