
:fragment:

The configuration that we could need in a properties file:
[source,properties]
.config/properties/application-kafka-env.properties
----
spring.cloud.stream.kafka.binder.brokers=localhost:9092 #<1>
----
<1> Configuration of the address of the Kafka server to connect to.

[IMPORTANT]
====
These values are by default but it could be different if you configured Kafka with other values .
====

If we configure a producer, we need to create the file application.properties or application.yml manually if it does not exist.
[source,properties]
.resources/application.properties
----
spring.cloud.stream.bindings.output.destination=greetings	#<1>
spring.cloud.stream.bindings.output.contentType= application/json		#<2>

----
<1> Kafka topic we use for outbound streams in our code.
<2> The contentType property tells Spring Cloud Stream to send our message objects as Strings in the streams.


[source,yml]
.resources/application.yml
----
spring:
  cloud:
    stream:
      kafka:
      bindings:
        greetings-out:
          destination: greetings	#<1>
          contentType: application/json	#<2>
	
----

<1> Kafka topic we use for outbound streams in our code.
<2> The contentType property tells Spring Cloud Stream to send our message objects as Strings in the streams.

If we configure a listener, we need to create the file application.properties or application.yml manually if it does not exist.
[source,properties]
.resources/application.properties
----
spring.cloud.stream.bindings.input.destination=greetings	#<1>
spring.cloud.stream.bindings.input.contentType= application/json	#<2>

----
<1> Kafka topic we use for inbound streams in our code.
<2> The contentType property tells Spring Cloud Stream to receive our message objects as Strings in the streams.

[source,yml]
.resources/application.yml
----
spring:
  cloud:
    stream:
      kafka:
      bindings:
        greetings-in:
          destination: greetings	#<1>
          contentType: application/json	#<2>
	
----

<1> Kafka topic we use for inbound streams in our code.
<2> The contentType property tells Spring Cloud Stream to recieve our message objects as Strings in the streams.
