apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: ${serviceName}
    labels:
      app: ${deploymentName}
  spec:
    ports:
    - port: 8080
      targetPort: 8080
      name: 8080-tcp
    selector:
      deploymentconfig: ${deploymentName}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${volume}
  spec:
    accessModes:
      - ReadWriteOnce 
    resources:
      requests:
        storage: 1Gi 
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: ${deploymentName}
  spec:
    replicas: 1
    selector:
      deploymentconfig: ${deploymentName}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          deploymentconfig: ${deploymentName}
      spec:
        volumes:
        - name: log
          persistentVolumeClaim:
               claimName: ${volume}      
        containers:
        - image: ${imageName}
          name: ${deploymentName}
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 800Mi
            requests:
              cpu: 200m
              memory: 500Mi
          volumeMounts:
            - mountPath: /log
              name: log
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - ${deploymentName}
        from:
          kind: ImageStreamTag
          name: ${imageName}:latest
      type: ImageChange
- apiVersion: v1
  kind: Route
  metadata:
    name: ${routeName}
  spec:
    host: ${routeName}-altemista.framework.helix.everis.cloud
    port:
        targetPort: 8080-tcp
    to:
        kind: Service
        name: ${serviceName}      
