
:fragment:

The http://docs.spring.io/spring-security/site/docs/current/reference/htmlsingle/#crypto[Crypto Module] of http://projects.spring.io/spring-security/[Spring Security] provides support for symmetric encryption and decryption using https://en.wikipedia.org/wiki/Advanced_Encryption_Standard[Advanced Encryption Standard (AES)].

Asymmetric encryption and decryption using https://en.wikipedia.org/wiki/RSA_(cryptosystem)[RSA] is also supported through the non-official https://github.com/dsyer/spring-security-rsa[Spring Security RSA].

Both algorithms have been chosen because they are the standard in modern cryptography.

{framework} provides convenience utility classes to ease some common tasks, such as reading or writing both public and private keys.

CAUTION: To use either _symmetric encryption and decryption using AES_ or _asymmetric encryption and decryption using RSA_ you need the full-strengh JCE installed in your JVM (it is not included by default). Please read the <<cloud-altemistafwk-common-cryptography-java>> section.

== Symmetric encryption and decryption using AES

Encryption and decryption operations are achieved through Spring `Encryptors` factory for commonly used encryptors for text and byte arrays.

Example symmetric encryption and decryption of texts:

[source]
----
include::{basedir}/cloud-altemistafwk-common-cryptography/src/test/java/cloud/altemista/fwk/test/cryptography/util/AESExampleTest.java[tags=text]
----
<1> Use `Encryptors.text` to retrieve a 256 bit AES-based `TextEncryptor`. The salt must be hex-encoded.
<2> Encryption example.
<3> Decryption example.

Example symmetric encryption and decryption of byte arrays:

[source]
----
include::{basedir}/cloud-altemistafwk-common-cryptography/src/test/java/cloud/altemista/fwk/test/cryptography/util/AESExampleTest.java[tags=binary]
----
<1> Use `Encryptors.standard` to retrieve a 256 bit AES-based `BytesEncryptor`.

== Asymmetric encryption and decryption using RSA

Example asymmetric encryption and decryption:

[source]
----
include::{basedir}/cloud-altemistafwk-common-cryptography/src/test/java/cloud/altemista/fwk/test/cryptography/util/RSAExampleTest.java[tags=text]
----
<1> The password for the Java key store.
<2> Use Spring Security RSA `KeyStoreKeyFactory` to actually extract the `KeyPair` from the Java key store. The key pair must be RSA-enconded.
<3> If the key pair does not have the same password as the key store, use `getKeyPair(String alias, char[] password)`.
<4> Use `RsaSecretEncryptor` to instantiate the RSA-based `RsaSecretEncryptor`.
<5> Encryption example.
<6> Decryption example.

RSA encryption and decryption can be used over byte arrays as well, as `RsaSecretEncryptor` implements both `TextEncryptor` and `BytesEncryptor`.

[source]
----
include::{basedir}/cloud-altemistafwk-common-cryptography/src/test/java/cloud/altemista/fwk/test/cryptography/util/RSAExampleTest.java[tags=binary]
----

TIP: The Java Keytool command to generate a Java keystore with a valid key pair: `keytool -keystore mykeystore.jks -genkey -alias myalias -keyalg RSA -keysize 2048`

== Reading Java key stores

{framework} utility class `KeyStoreUtil` can be used to read Java key stores, Java Secure Socket Extension (JSSE) key and trust managers, certificates, and public and private keys from Java key stores. Please refer to its Javadoc for details.
