
-- T_UNIT values
INSERT INTO T_UNIT (ID, NAME, GRAMS) VALUES (1, 'gram', 1);
INSERT INTO T_UNIT (ID, NAME, GRAMS) VALUES (2, 'kilogram', 1000);
INSERT INTO T_UNIT (ID, NAME, GRAMS) VALUES (3, 'pound', 454);

-- T_INGREDIENT values
INSERT INTO T_INGREDIENT (ID, NAME) VALUES (1, 'chocolate');
INSERT INTO T_INGREDIENT (ID, NAME) VALUES (2, 'cookie');

-- T_RECIPE values
INSERT INTO T_RECIPE (ID, NAME, BAKING_TEMP, BAKING_TIME) VALUES (1, 'chocolate cake', 180, 20);
INSERT INTO T_RECIPE (ID, NAME, BAKING_TEMP, BAKING_TIME) VALUES (2, 'chocolate cookies', 220, 10);
INSERT INTO T_RECIPE (ID, NAME, BAKING_TEMP, BAKING_TIME) VALUES (3, 'fish and chips', 180, 5);

-- T_RECIPE_INGREDIENT values
INSERT INTO T_RECIPE_INGREDIENT (ID, RECIPE_ID, INGREDIENT_ID, AMOUNT, UNIT_ID) VALUES (1, 1, 1, 1, 2);
INSERT INTO T_RECIPE_INGREDIENT (ID, RECIPE_ID, INGREDIENT_ID, AMOUNT, UNIT_ID) VALUES (2, 2, 1, 100, 1);
INSERT INTO T_RECIPE_INGREDIENT (ID, RECIPE_ID, INGREDIENT_ID, AMOUNT, UNIT_ID) VALUES (3, 2, 2, 200, 1);


-- DEMO_TABLE values
INSERT INTO DEMO_TABLE (KEY,
	INTEGER_FIELD, INT_FIELD, SMALLINT_FIELD, TINYINT_FIELD, BIGINT_FIELD,
	DECIMAL_FIELD, NUMERIC_FIELD, FLOAT_FIELD, DOUBLE_FIELD,
	DATE_FIELD, DATETIME_FIELD, TIMESTAMP_FIELD, TIME_FIELD,
	CHAR_FIELD, VARCHAR_FIELD, BINARY_FIELD, VARBINARY_FIELD,
	BLOB_FIELD
	
) VALUES (1001,
	NULL, NULL, NULL, NULL, NULL,
	NULL, NULL, NULL, NULL,
	NULL, NULL, NULL, NULL,
	NULL, NULL, NULL, NULL,
	NULL
);

INSERT INTO DEMO_TABLE (KEY,
	INTEGER_FIELD, INT_FIELD, SMALLINT_FIELD, TINYINT_FIELD, BIGINT_FIELD,
	DECIMAL_FIELD, NUMERIC_FIELD, FLOAT_FIELD, DOUBLE_FIELD,
	DATE_FIELD, DATETIME_FIELD, TIMESTAMP_FIELD, TIME_FIELD,
	CHAR_FIELD, VARCHAR_FIELD, BINARY_FIELD, VARBINARY_FIELD,
	BLOB_FIELD
	
) VALUES (1002,
	1, 2, 3, 4, 5,
	6, 7, 8.9, 10.11,
	NOW(), NOW(), NOW(), NOW(),
	'foo', 'bar', '62617a', '717578',
	'71757578'
);

INSERT INTO DEMO_TABLE (KEY,
	INTEGER_FIELD, INT_FIELD, SMALLINT_FIELD, TINYINT_FIELD, BIGINT_FIELD,
	DECIMAL_FIELD, NUMERIC_FIELD, FLOAT_FIELD, DOUBLE_FIELD,
	DATE_FIELD, DATETIME_FIELD, TIMESTAMP_FIELD, TIME_FIELD,
	CHAR_FIELD, VARCHAR_FIELD, BINARY_FIELD, VARBINARY_FIELD,
	BLOB_FIELD
	
) VALUES (1003,
	NULL, NULL, NULL, NULL, NULL,
	NULL, NULL, NULL, NULL,
	NULL, NULL, NULL, NULL,
	NULL, NULL, NULL, NULL,
	NULL
);
