
:fragment:

SWAGGER is an open standard for describing APIs https://swagger.io/specification/[Swagger Specification^] These APIs have been generated by Hyperledger Composer using the same vocabulary as defined in the model to describe the participants, applications, and transactions that were defined for this business network! It means that the SWAGGER APIs have obvious meaning to both the business and technical user.

Although Swagger is generally known for its user interface tools, it also provides the user with other tools, such as automation and test cases.At first, the popularity of the Swagger API was limited to the reach of small-scale organizations and individual developers. Most of the time, mechanisms that support machine readability are not available with RESTful APIs, but the Swagger API provided an easy and simple way of doing so. However, soon enough, with the help of an open source license from Apache 2.0, products and online services started offering Swagger as a part of their toolkit. This soon led to global companies, such as Apigee, Intuit, Microsoft, and IBM, to start endorsing the Swagger project publicly.

The configuration of Swagger mainly centers around the Docket bean. The {framework} `SwaggerConfig` class has the next structure to configure the application as a {framework} API Swagger

[source,java]
----
@EnableSwagger2// <!--1-->
public class SwaggerConfig {

	@Bean
	public Docket api() {
		return new Docket(DocumentationType.SWAGGER_2).select()// <!--2-->
				.apis(RequestHandlerSelectors.any())// <!--3-->
				.paths(PathSelectors.any()).build();// <!--4-->
	}
}
----
<1> Swagger 2 is enabled through the @EnableSwagger2 annotation.
<2> After the Docket bean is defined, its select() method returns an instance of ApiSelectorBuilder, which provides a way to control the endpoints exposed by Swagger.
<3> Apis() allows selection of RequestHandler's using a predicate. The example here uses an any predicate (default). Out of the box predicates provided are any, none, withClassAnnotation, withMethodAnnotation and basePackage.
<4> Paths() allows selection of Path's using a predicate. The example here uses an any predicate (default). Out of the box we provide predicates for regex, ant, any, none.

There are two ways for developing using Swagger: